import {
  StudentProfile,
  Assessment,
  LeaderboardEntry,
  RoleSkillGapAnalysis,
  RoadmapPhase,
  InternshipOpportunity,
  DepartmentMetric,
  CurriculumAnalysisResult,
  JobRequirement,
  CandidateApplication,
  Assignment,
  SkillDemandMetric,
  PlatformUser,
  AchievementBadge,
} from '@/types';

export const mockStudentProfile: StudentProfile = {
  id: 'std-98214',
  name: 'Manutej Reddy',
  email: 'manutej.reddy@skillbridge.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  headline: 'Aspiring Systems & AI Builder | Full-Stack & Distributed Systems Engineer',
  targetRole: 'AI Systems Engineer',
  college: 'HITAM',
  department: 'CSE',
  branch: 'Computer Science & Engineering',
  degree: 'B.Tech',
  graduationYear: '2026',
  careerGoal: 'High-Impact AI Systems Internship',
  careerReadinessScore: 92,
  city: 'Hyderabad',
  state: 'Telangana',
  country: 'India',
  academic: {
    college: 'HITAM',
    department: 'CSE',
    branch: 'Computer Science & Engineering',
    degree: 'B.Tech',
    graduationYear: '2026',
    year: '3rd Year',
    semester: '6th Semester',
    cgpa: 9.14,
    studentId: 'HITAM-CSE-2023-042',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
  },
  professional: {
    githubUrl: 'https://github.com/manutejreddy',
    linkedinUrl: 'https://linkedin.com/in/manutejreddy',
    portfolioUrl: 'https://manutejreddy.dev',
    resumeUrl: '/resumes/manutej-reddy-resume.pdf',
    bio: 'Passionate about bridging high-performance backend systems with modern LLM architectures. Contributor to open-source inference pipelines and winner of 3 national collegiate hackathons.',
    totalProjects: 14,
    hackathonWins: 3,
    researchPapers: 1,
    openSourceContributions: 48,
    careerGoal: 'Internship',
    githubScore: 890,
  },
  builderScores: {
    overall: 885,
    execution: 92,
    leadership: 84,
    innovation: 90,
    problemSolving: 94,
    consistency: 82,
  },
  employabilityScore: 91,
  verifiedSkills: [
    {
      id: 'vs-1',
      name: 'Python & FastAPI',
      category: 'Programming',
      level: 'Expert',
      score: 95,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Aug 14, 2025',
      verificationCode: 'SB-PY-95821',
      evidenceCount: 6,
    },
    {
      id: 'vs-2',
      name: 'PyTorch & Transformers',
      category: 'AI & ML',
      level: 'Advanced',
      score: 88,
      verificationSources: ['Project', 'Assessment', 'Certification'],
      verifiedDate: 'Oct 02, 2025',
      verificationCode: 'SB-AI-88301',
      evidenceCount: 4,
    },
    {
      id: 'vs-3',
      name: 'TypeScript & Next.js',
      category: 'Programming',
      level: 'Advanced',
      score: 86,
      verificationSources: ['Project', 'Assessment'],
      verifiedDate: 'Nov 19, 2025',
      verificationCode: 'SB-TS-86102',
      evidenceCount: 5,
    },
    {
      id: 'vs-4',
      name: 'PostgreSQL & pgvector',
      category: 'Database',
      level: 'Advanced',
      score: 89,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Jan 10, 2026',
      verificationCode: 'SB-DB-89412',
      evidenceCount: 3,
    },
    {
      id: 'vs-5',
      name: 'Docker & Kubernetes',
      category: 'DevOps',
      level: 'Intermediate',
      score: 74,
      verificationSources: ['Certification', 'Project'],
      verifiedDate: 'Jan 28, 2026',
      verificationCode: 'SB-DO-74291',
      evidenceCount: 2,
    },
    {
      id: 'vs-6',
      name: 'Distributed Systems & RPC',
      category: 'Programming',
      level: 'Intermediate',
      score: 78,
      verificationSources: ['Assessment', 'Faculty Validation'],
      verifiedDate: 'Feb 15, 2026',
      verificationCode: 'SB-DS-78330',
      evidenceCount: 3,
    },
  ],
  evidences: [
    {
      id: 'ev-1',
      title: 'Real-time Multimodal Vector Retrieval Engine',
      type: 'GitHub Repo',
      url: 'https://github.com/aarav-sharma-builder/vectormind-core',
      description: 'Engineered high-throughput HNSW index search serving 40k QPS with sub-15ms p99 latency in C++ and Python bindings.',
      date: 'Jan 2026',
      impactScore: 96,
      verified: true,
    },
    {
      id: 'ev-2',
      title: 'SmartCampus IoT Edge Guardian (1st Place)',
      type: 'Hackathon Win',
      url: 'https://devpost.com/software/smartcampus-edge',
      description: 'Led a 4-person engineering team to build on-device edge vision models for university energy conservation.',
      date: 'Dec 2025',
      impactScore: 91,
      verified: true,
    },
    {
      id: 'ev-3',
      title: 'Quantization & Sparse Attention in Small Models',
      type: 'Research Paper',
      url: 'https://arxiv.org/abs/sample-quant-2025',
      description: 'Co-authored paper presented at Student AI Symposium benchmarking 4-bit INT quantization loss on Llama architectures.',
      date: 'Nov 2025',
      impactScore: 88,
      verified: true,
    },
    {
      id: 'ev-4',
      title: 'vLLM Kernel Optimization Contribution',
      type: 'Open Source PR',
      url: 'https://github.com/vllm-project/vllm/pull/sample-pr',
      description: 'Merged PR optimizing CUDA memory buffer allocation for batched speculative decoding.',
      date: 'Feb 2026',
      impactScore: 94,
      verified: true,
    },
  ],
};

export const mockRadarData = [
  { subject: 'Programming', A: 95, fullMark: 100, benchmark: 80 },
  { subject: 'System Design', A: 82, fullMark: 100, benchmark: 75 },
  { subject: 'AI / Machine Learning', A: 88, fullMark: 100, benchmark: 70 },
  { subject: 'Cloud & DevOps', A: 76, fullMark: 100, benchmark: 65 },
  { subject: 'Problem Solving', A: 94, fullMark: 100, benchmark: 85 },
  { subject: 'Communication', A: 84, fullMark: 100, benchmark: 78 },
];

export const mockProgressTrend = [
  { month: 'Sep', builderScore: 720, industryReadiness: 68 },
  { month: 'Oct', builderScore: 750, industryReadiness: 73 },
  { month: 'Nov', builderScore: 795, industryReadiness: 79 },
  { month: 'Dec', builderScore: 825, industryReadiness: 83 },
  { month: 'Jan', builderScore: 855, industryReadiness: 87 },
  { month: 'Feb', builderScore: 885, industryReadiness: 91 },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'asm-1',
    title: 'Advanced Python & Concurrency Benchmark',
    category: 'Programming',
    durationMinutes: 45,
    questionsCount: 15,
    difficulty: 'Hard',
    skillsEvaluated: ['AsyncIO', 'GIL', 'Memory Profiling', 'Generators'],
    passingScore: 75,
    completed: true,
    score: 94,
    percentile: 98.4,
    questions: [
      {
        id: 'q1',
        question: 'How does Python\'s asyncio event loop handle CPU-bound vs I/O-bound tasks in modern runtimes?',
        options: [
          'AsyncIO automatically spawns OS threads for heavy math computations',
          'CPU-bound tasks block the event loop unless offloaded to ProcessPoolExecutor or native threads',
          'The GIL switches threads every microsecond regardless of coroutine suspension',
          'AsyncIO uses kernel fibers to bypass Python GIL limitations'
        ],
        correctAnswer: 1,
        explanation: 'AsyncIO is cooperative single-threaded concurrency; CPU-intensive calculations will starve the event loop unless delegated to separate processes or worker threads.'
      },
      {
        id: 'q2',
        question: 'Which method provides zero-copy deserialization of memory buffers in Python?',
        options: ['pickle.loads()', 'json.loads()', 'memoryview() and struct.unpack_from()', 'io.StringIO()'],
        correctAnswer: 2,
        explanation: 'memoryview allows Python code to access the internal data of an object that supports the buffer protocol without copying.'
      }
    ]
  },
  {
    id: 'asm-2',
    title: 'LLM Engineering & Vector Search Architecture',
    category: 'AI',
    durationMinutes: 40,
    questionsCount: 12,
    difficulty: 'Hard',
    skillsEvaluated: ['RAG', 'HNSW Indexing', 'Context Windows', 'Fine-Tuning'],
    passingScore: 70,
    completed: true,
    score: 88,
    percentile: 93.1,
    questions: [
      {
        id: 'q-ai-1',
        question: 'What is the primary advantage of HNSW (Hierarchical Navigable Small World) graphs over IVFFlat for vector retrieval?',
        options: [
          'HNSW requires zero memory indexing overhead',
          'HNSW provides logarithmic search time with superior recall-latency tradeoff without retraining centroids',
          'HNSW executes exclusively on GPU VRAM',
          'IVFFlat always yields higher accuracy at high dimensions'
        ],
        correctAnswer: 1,
        explanation: 'HNSW builds multi-layer graph structures delivering near sub-linear search latency and high recall even without cluster retraining.'
      }
    ]
  },
  {
    id: 'asm-3',
    title: 'Cloud Native & Kubernetes Pod Lifecycle',
    category: 'Cloud',
    durationMinutes: 30,
    questionsCount: 10,
    difficulty: 'Medium',
    skillsEvaluated: ['K8s Probes', 'Ingress', 'Helm', 'CSI Storage'],
    passingScore: 70,
    completed: false,
    questions: [
      {
        id: 'q-cl-1',
        question: 'When should a startupProbe be configured in a Kubernetes pod specification?',
        options: [
          'To continuously check if the app is alive during normal operation',
          'For legacy or slow-starting containers to prevent readiness/liveness probes killing the pod prematurely',
          'To manage persistent volume mounting timeouts',
          'To route external ingress traffic before DNS propagation'
        ],
        correctAnswer: 1,
        explanation: 'startupProbe disables liveness and readiness checks until it succeeds, protecting slow-booting applications from aggressive restarts.'
      }
    ]
  },
  {
    id: 'asm-4',
    title: 'Analytical Aptitude & Quantitative Reasoning',
    category: 'Aptitude',
    durationMinutes: 35,
    questionsCount: 20,
    difficulty: 'Medium',
    skillsEvaluated: ['Data Interpretation', 'Probability', 'Logical Deduction'],
    passingScore: 75,
    completed: true,
    score: 92,
    percentile: 95.8,
  },
  {
    id: 'asm-5',
    title: 'Executive Technical Communication',
    category: 'Communication',
    durationMinutes: 25,
    questionsCount: 10,
    difficulty: 'Easy',
    skillsEvaluated: ['Stakeholder Sync', 'Architecture Diagrams', 'Incident Post-Mortems'],
    passingScore: 70,
    completed: true,
    score: 85,
    percentile: 89.2,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    studentName: 'Devansh Kulkarni',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 942,
    verifiedSkillsCount: 9,
    level: 22,
    xp: 3840,
    badge: 'Elite Vanguard',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 2,
    studentName: 'Priya Nambiar',
    college: 'National Tech University',
    department: 'AIML',
    builderScore: 918,
    verifiedSkillsCount: 8,
    level: 20,
    xp: 3200,
    badge: 'Master Architect',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 3,
    studentName: 'Aarav Sharma (You)',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 885,
    verifiedSkillsCount: 6,
    level: 18,
    xp: 2450,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 4,
    studentName: 'Rohan Mehra',
    college: 'Metropolitan Institute of Science',
    department: 'IT',
    builderScore: 864,
    verifiedSkillsCount: 7,
    level: 16,
    xp: 1980,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 5,
    studentName: 'Ananya Iyer',
    college: 'Southern Institute of Engineering',
    department: 'ECE',
    builderScore: 842,
    verifiedSkillsCount: 5,
    level: 15,
    xp: 1820,
    badge: 'Senior Builder',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
  },
];

export const mockRoleSkillGap: Record<string, RoleSkillGapAnalysis> = {
  'AI Engineer': {
    targetRole: 'AI Engineer',
    matchPercentage: 86,
    totalRequiredSkills: 8,
    matchedSkillsCount: 6,
    missingSkills: ['Kubernetes / Triton Inference Server', 'Graph Neural Networks & DGL'],
    overview: 'Strong foundation in Python, Vector DBs, and LLM orchestration. You are 2 critical infrastructure skills away from 95%+ enterprise alignment.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'PyTorch & Transformers',
        requiredLevel: 'Expert',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 90,
        recommendedCourse: 'Deep Learning Systems Architecture',
      },
      {
        skill: 'pgvector & Vector Databases',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'LLM Orchestration & RAG',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 92,
        recommendedCourse: 'Advanced Agentic Patterns with LangGraph',
      },
      {
        skill: 'Triton Inference Server / vLLM',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 20,
        recommendedCourse: 'High-Throughput Model Serving with vLLM & TensorRT',
      },
      {
        skill: 'Distributed Training (FSDP / DeepSpeed)',
        requiredLevel: 'Intermediate',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 45,
        recommendedCourse: 'Distributed Machine Learning at Scale',
      },
    ],
  },
  'Backend Developer': {
    targetRole: 'Backend Developer',
    matchPercentage: 92,
    totalRequiredSkills: 7,
    matchedSkillsCount: 6,
    missingSkills: ['Kafka / Event-Driven Architecture'],
    overview: 'Exceptional backend capabilities with proven SQL performance, API design, and asynchronous concurrency.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Advanced',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PostgreSQL Optimization',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'Kafka Message Queuing',
        requiredLevel: 'Advanced',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 40,
        recommendedCourse: 'Enterprise Event Streaming with Apache Kafka',
      },
    ],
  },
  'Data Analyst': {
    targetRole: 'Data Analyst',
    matchPercentage: 78,
    totalRequiredSkills: 6,
    matchedSkillsCount: 4,
    missingSkills: ['PowerBI / Tableau', 'Advanced Business Statistics'],
    overview: 'Solid programmatic and SQL foundation; needs dashboarding and executive stakeholder KPI modeling practice.',
    skillGaps: [
      {
        skill: 'SQL Querying',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PowerBI / Tableau',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 15,
        recommendedCourse: 'Executive BI & Dashboards Masterclass',
      },
    ],
  },
};

export const mockRoadmapPhases: RoadmapPhase[] = [
  {
    id: 'phase-1',
    phaseNumber: 1,
    title: 'Foundation',
    description: 'Master core algorithmic problem solving, modern Python 3.12+, and relational database schema design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Advanced Data Structures & Algorithms', provider: 'SkillBridge Core', duration: '6 weeks', completed: true },
      { title: 'High Performance Python & Concurrency', provider: 'SkillBridge Core', duration: '4 weeks', completed: true },
    ],
    projects: [
      { title: 'Concurrent Cache with LRU & TTL Eviction', description: 'Thread-safe in-memory key-value store', techStack: ['Python', 'Threading', 'TCP Sockets'], completed: true },
    ],
    assessments: [
      { title: 'Data Structures Benchmark', category: 'Programming', completed: true },
      { title: 'Quantitative Aptitude Level 1', category: 'Aptitude', completed: true },
    ],
  },
  {
    id: 'phase-2',
    phaseNumber: 2,
    title: 'Core',
    description: 'Deep dive into REST & gRPC API architecture, vector databases (pgvector), and modern microservice design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Production FastAPI & Distributed Systems', provider: 'Coursera Enterprise', duration: '5 weeks', completed: true },
      { title: 'Vector Embeddings & Semantic Search', provider: 'DeepLearning.AI', duration: '3 weeks', completed: true },
    ],
    projects: [
      { title: 'Hybrid Lexical-Vector Search Engine', description: 'Sub-20ms multi-tenant vector retriever on PostgreSQL', techStack: ['FastAPI', 'pgvector', 'Redis'], completed: true },
    ],
    assessments: [
      { title: 'Advanced Python & Concurrency Benchmark', category: 'Programming', completed: true },
    ],
  },
  {
    id: 'phase-3',
    phaseNumber: 3,
    title: 'Advanced',
    description: 'LLM fine-tuning, Quantization (4-bit/8-bit), RAG evaluation metrics (Ragas), and Triton inference pipelines.',
    status: 'in_progress',
    progressPercentage: 65,
    courses: [
      { title: 'LLM Inference Optimization & vLLM Internals', provider: 'SkillBridge Masterclass', duration: '4 weeks', completed: true },
      { title: 'Kubernetes for Machine Learning Workloads', provider: 'Cloud Native Academy', duration: '4 weeks', completed: false },
    ],
    projects: [
      { title: 'Enterprise Document Intelligence with LangGraph', description: 'Autonomous agentic multi-doc synthesis pipeline', techStack: ['FastAPI', 'LangGraph', 'Docker'], completed: true },
      { title: 'Triton Server TensorRT Deployment', description: 'Deploying quantized Mistral-7B at 80 tokens/sec', techStack: ['Triton', 'TensorRT-LLM', 'CUDA'], completed: false },
    ],
    assessments: [
      { title: 'LLM Engineering & Vector Search Architecture', category: 'AI', completed: true },
      { title: 'Cloud Native & Kubernetes Pod Lifecycle', category: 'Cloud', completed: false },
    ],
  },
  {
    id: 'phase-4',
    phaseNumber: 4,
    title: 'Industry Ready',
    description: 'System design capstone, live client simulations, mock technical interviews, and recruiter talent discovery indexing.',
    status: 'locked',
    progressPercentage: 0,
    courses: [
      { title: 'Large Scale Distributed System Design', provider: 'SkillBridge Enterprise', duration: '4 weeks', completed: false },
      { title: 'AI Ethics, Guardrails & SOC2 Compliance', provider: 'Security Institute', duration: '2 weeks', completed: false },
    ],
    projects: [
      { title: 'Full-Scale Enterprise Workforce Intelligence Platform', description: 'Multi-tenant high-availability microservices', techStack: ['Next.js 15', 'FastAPI', 'PostgreSQL', 'K8s'], completed: false },
    ],
    assessments: [
      { title: 'Full Enterprise Architecture Capstone Exam', category: 'Programming', completed: false },
    ],
  },
];

export const mockInternships: InternshipOpportunity[] = [
  {
    id: 'job-101',
    role: 'AI Infrastructure Engineer Intern',
    company: 'Anthropic Labs Partner Network',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    location: 'San Francisco, CA (Hybrid / Remote)',
    type: 'Hybrid',
    stipend: '$7,500 / month',
    duration: '6 Months',
    matchScore: 94,
    requiredSkills: ['Python', 'PyTorch', 'Vector Search', 'FastAPI'],
    postedDate: '2 days ago',
    applied: false,
    applicantsCount: 42,
    description: 'Help architect low-latency inference pipelines and multi-tenant vector indexes for next-generation intelligence tooling.',
  },
  {
    id: 'job-102',
    role: 'Backend Platform Engineer Intern',
    company: 'Stripe Scale Program',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    location: 'New York, NY (On-site)',
    type: 'On-site',
    stipend: '$8,200 / month',
    duration: '3 Months',
    matchScore: 91,
    requiredSkills: ['Python', 'PostgreSQL', 'Distributed Systems', 'Docker'],
    postedDate: '3 days ago',
    applied: true,
    applicantsCount: 118,
    description: 'Work alongside core payments infrastructure teams optimizing high-throughput transaction ledgers and microservices.',
  },
  {
    id: 'job-103',
    role: 'Full-Stack AI Software Intern',
    company: 'Linear Ventures',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    location: 'Remote',
    type: 'Remote',
    stipend: '$6,800 / month',
    duration: '6 Months',
    matchScore: 88,
    requiredSkills: ['TypeScript', 'Next.js', 'FastAPI', 'Tailwind CSS'],
    postedDate: '5 days ago',
    applied: false,
    applicantsCount: 67,
    description: 'Build polished, responsive user interfaces and robust APIs for automated sprint intelligence and code analysis.',
  },
];

// Institute Portal Seed Data
export const mockDepartmentMetrics: DepartmentMetric[] = [
  {
    name: 'CSE',
    totalStudents: 320,
    overallReadiness: 86,
    programming: 91,
    cloud: 78,
    ai: 88,
    devOps: 74,
    dataScience: 82,
  },
  {
    name: 'AIML',
    totalStudents: 180,
    overallReadiness: 89,
    programming: 88,
    cloud: 72,
    ai: 95,
    devOps: 68,
    dataScience: 94,
  },
  {
    name: 'IT',
    totalStudents: 240,
    overallReadiness: 81,
    programming: 84,
    cloud: 85,
    ai: 70,
    devOps: 82,
    dataScience: 75,
  },
  {
    name: 'ECE',
    totalStudents: 210,
    overallReadiness: 72,
    programming: 75,
    cloud: 60,
    ai: 66,
    devOps: 58,
    dataScience: 69,
  },
];

export const mockCurriculumAnalysis: CurriculumAnalysisResult = {
  syllabusTitle: 'B.Tech CSE - 6th Semester Advanced Computing Curriculum (2025-2026)',
  department: 'Computer Science & Engineering',
  semester: '6th Semester',
  industryRelevanceScore: 78,
  totalTopicsAnalyzed: 44,
  modernTopicsCount: 31,
  missingTopics: [
    {
      topic: 'Vector Databases & Embedding Indexing (HNSW / pgvector)',
      importance: 'Critical',
      industryUsagePercentage: 88,
      recommendedModule: 'Module 4: Advanced Data Storage & RAG Systems',
    },
    {
      topic: 'Cloud Native CI/CD & Kubernetes Manifests',
      importance: 'Critical',
      industryUsagePercentage: 92,
      recommendedModule: 'Module 5: Modern DevOps & Container Orchestration',
    },
    {
      topic: 'LLM Fine-Tuning, Quantization & Prompt Optimization',
      importance: 'High',
      industryUsagePercentage: 84,
      recommendedModule: 'Module 3: Contemporary Applied Machine Intelligence',
    },
    {
      topic: 'gRPC & Protocol Buffers for Low-Latency Microservices',
      importance: 'Moderate',
      industryUsagePercentage: 76,
      recommendedModule: 'Module 2: Distributed Systems Communication',
    },
  ],
  outdatedTopics: [
    'SOAP XML Web Services & WSDL Specifications',
    'CORBA Distributed Object Architectures',
    'Legacy JSP / Servlet Form Submissions',
  ],
  suggestedImprovements: [
    'Replace legacy SOAP XML laboratory exercises with OpenAPI 3.1 & FastAPI Async handlers.',
    'Introduce 4 weeks of hands-on containerization labs (Docker Compose + K8s MiniKube).',
    'Integrate vector search laboratory modules using PostgreSQL + pgvector for unstructured retrieval.',
    'Align assessment rubrics with GitHub Builder evidence and automated unit-test grading.',
  ],
  topSkillsCovered: ['Data Structures', 'Operating Systems', 'RDBMS & SQL', 'Computer Networks', 'Intro to ML'],
};

// Industry Portal Seed Data
export const mockJobRequirements: JobRequirement[] = [
  {
    id: 'req-201',
    title: 'AI Systems Engineer (Graduate 2026)',
    department: 'Applied AI',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'Bangalore / Hyderabad (Hybrid)',
    type: 'Full-Time',
    salaryRange: '$85,000 - $115,000',
    minMatchScore: 80,
    requiredSkills: ['Python', 'PyTorch', 'FastAPI', 'pgvector', 'Docker'],
    preferredSkills: ['vLLM', 'Kubernetes', 'LangGraph'],
    activeApplicants: 34,
    createdAt: 'Mar 01, 2026',
    status: 'Active',
  },
  {
    id: 'req-202',
    title: 'Full-Stack SaaS Platform Engineer',
    department: 'Core Product',
    experienceLevel: 'Associate (1-3 yrs)',
    location: 'Remote (US/India)',
    type: 'Full-Time',
    salaryRange: '$90,000 - $125,000',
    minMatchScore: 75,
    requiredSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind CSS'],
    preferredSkills: ['Redis', 'AWS Lambda', 'GraphQL'],
    activeApplicants: 52,
    createdAt: 'Feb 24, 2026',
    status: 'Active',
  },
  {
    id: 'req-203',
    title: 'Cloud Infrastructure & DevOps Intern',
    department: 'Site Reliability',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'San Francisco, CA',
    type: 'Internship',
    salaryRange: '$6,000 / month',
    minMatchScore: 70,
    requiredSkills: ['Docker', 'Kubernetes', 'Linux Internals', 'Python/Go'],
    preferredSkills: ['Terraform', 'Prometheus', 'Grafana'],
    activeApplicants: 19,
    createdAt: 'Feb 28, 2026',
    status: 'Active',
  },
];

export const mockCandidatesPipeline: CandidateApplication[] = [
  {
    id: 'cand-1',
    studentId: 'std-98214',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    institution: 'Apex Institute of Technology',
    department: 'CSE',
    branch: 'Computer Science & Engineering',
    degree: 'B.Tech',
    graduationYear: '2026',
    location: 'Hyderabad, Telangana',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 885,
    employabilityScore: 91,
    careerReadinessScore: 92,
    githubScore: 890,
    matchScore: 94,
    stage: 'Interview',
    appliedDate: 'Mar 03, 2026',
    topSkills: ['Python', 'FastAPI', 'PyTorch', 'pgvector'],
    githubUrl: 'https://github.com/aarav-sharma-builder',
    linkedinUrl: 'https://linkedin.com/in/aarav-sharma-ai',
    portfolioUrl: 'https://aarav-sharma.dev',
    resumeUrl: '/resumes/aarav-sharma-resume.pdf',
    verifiedSkills: [
      { name: 'PyTorch & Transformers', category: 'AI & ML', level: 'Advanced', score: 92, sources: ['GitHub Verified', 'Assessment Verified', 'Project Verified'] },
      { name: 'FastAPI Microservices', category: 'Programming', level: 'Advanced', score: 88, sources: ['Assessment Verified', 'GitHub Verified'] },
      { name: 'pgvector & Embeddings', category: 'Database', level: 'Advanced', score: 90, sources: ['Project Verified', 'GitHub Verified'] },
      { name: 'Distributed Caching', category: 'Systems', level: 'Intermediate', score: 84, sources: ['Assessment Verified'] },
    ],
    projects: [
      {
        title: 'HNSW Vector Search Engine in Python/C++',
        techStack: ['Python', 'C++', 'FastAPI', 'Docker'],
        githubUrl: 'https://github.com/aarav-sharma-builder/hnsw-vector-core',
        projectScore: 95,
        description: 'Sub-millisecond approximate nearest neighbor indexing over 1M 768-dim embeddings.',
      },
      {
        title: 'Multi-Agent Code Review Bot with LangGraph',
        techStack: ['Python', 'LangGraph', 'Redis', 'Gemini API'],
        githubUrl: 'https://github.com/aarav-sharma-builder/ai-code-reviewer',
        projectScore: 91,
        description: 'Automated GitHub PR analyzer with AST parsing and security lint checks.',
      },
    ],
    certifications: [
      { title: 'DeepLearning.AI Transformers Specialization', issuer: 'Coursera', date: 'Jan 2026', score: 98 },
      { title: 'AWS Certified Solutions Architect Associate', issuer: 'Amazon Web Services', date: 'Nov 2025', score: 92 },
    ],
    assessments: [
      { title: 'AI & LLM Architecture Benchmark', score: 94, passed: true, date: 'Feb 15, 2026' },
      { title: 'Advanced Python Concurrency', score: 90, passed: true, date: 'Jan 28, 2026' },
    ],
  },
  {
    id: 'cand-2',
    studentId: 'std-98215',
    name: 'Devansh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    institution: 'Apex Institute of Technology',
    department: 'CSE',
    branch: 'Computer Science & Engineering',
    degree: 'B.Tech',
    graduationYear: '2026',
    location: 'Bengaluru, Karnataka',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 942,
    employabilityScore: 96,
    careerReadinessScore: 97,
    githubScore: 960,
    matchScore: 98,
    stage: 'Selected',
    appliedDate: 'Mar 01, 2026',
    topSkills: ['Python', 'C++', 'CUDA', 'Distributed Systems'],
    githubUrl: 'https://github.com/devansh-k-vanguard',
    linkedinUrl: 'https://linkedin.com/in/devansh-kulkarni',
    portfolioUrl: 'https://devansh.tech',
    resumeUrl: '/resumes/devansh-kulkarni-resume.pdf',
    verifiedSkills: [
      { name: 'CUDA Kernel Optimization', category: 'AI & ML', level: 'Expert', score: 96, sources: ['GitHub Verified', 'Project Verified'] },
      { name: 'C++ Systems Programming', category: 'Programming', level: 'Advanced', score: 94, sources: ['Assessment Verified', 'GitHub Verified'] },
      { name: 'Distributed Consensus (Raft)', category: 'Systems', level: 'Advanced', score: 92, sources: ['GitHub Verified', 'Assessment Verified'] },
    ],
    projects: [
      {
        title: 'Custom Tensor Operations on GPU with CUDA',
        techStack: ['C++', 'CUDA', 'PyTorch', 'CMake'],
        githubUrl: 'https://github.com/devansh-k-vanguard/cuda-tensor-ops',
        projectScore: 98,
        description: 'Fused FlashAttention kernels speeding up token generation by 2.4x.',
      },
    ],
    certifications: [
      { title: 'NVIDIA Deep Learning Institute CUDA C/C++', issuer: 'NVIDIA', date: 'Dec 2025', score: 96 },
    ],
    assessments: [
      { title: 'High-Concurrency Systems Evaluation', score: 96, passed: true, date: 'Feb 10, 2026' },
    ],
  },
  {
    id: 'cand-3',
    studentId: 'std-98216',
    name: 'Priya Nambiar',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    college: 'National Tech University',
    institution: 'National Tech University',
    department: 'AIML',
    branch: 'Artificial Intelligence & ML',
    degree: 'B.Tech',
    graduationYear: '2026',
    location: 'Chennai, Tamil Nadu',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 918,
    employabilityScore: 93,
    careerReadinessScore: 94,
    githubScore: 910,
    matchScore: 92,
    stage: 'Assessment',
    appliedDate: 'Mar 04, 2026',
    topSkills: ['PyTorch', 'Transformers', 'FastAPI', 'MLOps'],
    githubUrl: 'https://github.com/priya-nambiar-ai',
    linkedinUrl: 'https://linkedin.com/in/priya-nambiar-ml',
    portfolioUrl: 'https://priyanambiar.ai',
    resumeUrl: '/resumes/priya-nambiar-resume.pdf',
    verifiedSkills: [
      { name: 'Transformers Fine-tuning', category: 'AI & ML', level: 'Advanced', score: 93, sources: ['Assessment Verified', 'GitHub Verified'] },
      { name: 'MLOps Pipeline Automation', category: 'DevOps', level: 'Advanced', score: 89, sources: ['Project Verified', 'Assessment Verified'] },
    ],
    projects: [
      {
        title: 'QLoRA Quantized LLM Fine-Tuner CLI',
        techStack: ['Python', 'PEFT', 'HuggingFace', 'Docker'],
        githubUrl: 'https://github.com/priya-nambiar-ai/qlora-tuner-cli',
        projectScore: 93,
        description: 'Parameter-efficient 4-bit fine-tuning pipeline for domain-specific coding assistants.',
      },
    ],
    certifications: [
      { title: 'Google Professional Machine Learning Engineer', issuer: 'Google Cloud', date: 'Jan 2026', score: 91 },
    ],
    assessments: [
      { title: 'Machine Learning Infrastructure & MLOps', score: 92, passed: true, date: 'Feb 20, 2026' },
    ],
  },
  {
    id: 'cand-4',
    studentId: 'std-98217',
    name: 'Rohan Mehra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    college: 'Metropolitan Institute of Science',
    institution: 'Metropolitan Institute of Science',
    department: 'IT',
    branch: 'Information Technology',
    degree: 'B.Tech',
    graduationYear: '2026',
    location: 'Pune, Maharashtra',
    targetRole: 'Full-Stack SaaS Platform Engineer',
    jobId: 'req-202',
    builderScore: 864,
    employabilityScore: 89,
    careerReadinessScore: 88,
    githubScore: 875,
    matchScore: 88,
    stage: 'Shortlisted',
    appliedDate: 'Mar 05, 2026',
    topSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind'],
    githubUrl: 'https://github.com/rohan-mehra-dev',
    linkedinUrl: 'https://linkedin.com/in/rohan-mehra-tech',
    portfolioUrl: 'https://rohanmehra.dev',
    resumeUrl: '/resumes/rohan-mehra-resume.pdf',
    verifiedSkills: [
      { name: 'TypeScript & Next.js Full-Stack', category: 'Programming', level: 'Advanced', score: 90, sources: ['GitHub Verified', 'Assessment Verified', 'Project Verified'] },
      { name: 'PostgreSQL Relational Design', category: 'Database', level: 'Advanced', score: 86, sources: ['Assessment Verified'] },
    ],
    projects: [
      {
        title: 'Multi-Tenant Collaborative Workspace Platform',
        techStack: ['Next.js', 'TypeScript', 'Prisma', 'Tailwind', 'PostgreSQL'],
        githubUrl: 'https://github.com/rohan-mehra-dev/saas-workspace-core',
        projectScore: 89,
        description: 'Enterprise workspace app with real-time comments, document branching, and role-based permissions.',
      },
    ],
    certifications: [
      { title: 'Meta Front-End Developer Professional Certificate', issuer: 'Meta', date: 'Oct 2025', score: 94 },
    ],
    assessments: [
      { title: 'Full-Stack React & Next.js Architecture', score: 88, passed: true, date: 'Jan 12, 2026' },
    ],
  },
  {
    id: 'cand-5',
    studentId: 'std-98218',
    name: 'Ananya Iyer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
    college: 'Southern Institute of Engineering',
    institution: 'Southern Institute of Engineering',
    department: 'ECE',
    branch: 'Electronics & Communication',
    degree: 'B.Tech',
    graduationYear: '2026',
    location: 'Bengaluru, Karnataka',
    targetRole: 'Cloud Infrastructure & DevOps Intern',
    jobId: 'req-203',
    builderScore: 842,
    employabilityScore: 86,
    careerReadinessScore: 87,
    githubScore: 850,
    matchScore: 85,
    stage: 'Matched',
    appliedDate: 'Mar 06, 2026',
    topSkills: ['Docker', 'Linux', 'Python', 'K8s'],
    githubUrl: 'https://github.com/ananya-iyer-cloud',
    linkedinUrl: 'https://linkedin.com/in/ananya-iyer-infra',
    portfolioUrl: 'https://ananyaiyer.cloud',
    resumeUrl: '/resumes/ananya-iyer-resume.pdf',
    verifiedSkills: [
      { name: 'Docker & Container Security', category: 'DevOps', level: 'Advanced', score: 88, sources: ['GitHub Verified', 'Assessment Verified'] },
      { name: 'Kubernetes Pod Networking', category: 'Cloud', level: 'Intermediate', score: 83, sources: ['Assessment Verified'] },
    ],
    projects: [
      {
        title: 'Zero-Downtime Blue/Green Deployment Operator',
        techStack: ['Go', 'Kubernetes', 'Docker', 'Helm'],
        githubUrl: 'https://github.com/ananya-iyer-cloud/k8s-bluegreen-operator',
        projectScore: 87,
        description: 'Automated progressive canary delivery controller with Prometheus metrics rollback triggers.',
      },
    ],
    certifications: [
      { title: 'Certified Kubernetes Application Developer (CKAD)', issuer: 'CNCF / Linux Foundation', date: 'Feb 2026', score: 90 },
    ],
    assessments: [
      { title: 'Cloud Infrastructure & DevOps Mastery', score: 86, passed: true, date: 'Feb 25, 2026' },
    ],
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-1',
    title: 'High-Throughput Vector Index Benchmark in Python/C++',
    type: 'Coding Test',
    roleTarget: 'AI Systems Engineer',
    duration: '90 mins',
    totalAssigned: 45,
    submissionsCount: 38,
    averageScore: 82.4,
    status: 'Active',
    dueDate: 'Mar 18, 2026',
  },
  {
    id: 'asg-2',
    title: 'Enterprise Multi-Tenant SaaS DB Schema Design',
    type: 'Case Study',
    roleTarget: 'Full-Stack Platform Engineer',
    duration: '2 Days Takehome',
    totalAssigned: 30,
    submissionsCount: 26,
    averageScore: 88.0,
    status: 'Active',
    dueDate: 'Mar 20, 2026',
  },
  {
    id: 'asg-3',
    title: 'Fault-Tolerant K8s Pod Scheduling Simulator',
    type: 'System Design Challenge',
    roleTarget: 'Cloud Infrastructure Intern',
    duration: '120 mins',
    totalAssigned: 22,
    submissionsCount: 19,
    averageScore: 76.5,
    status: 'Active',
    dueDate: 'Mar 22, 2026',
  },
];

// Admin Portal Seed Data
export const mockSkillDemandMetrics: SkillDemandMetric[] = [
  {
    skill: 'LLM Orchestration & RAG',
    category: 'AI / Machine Learning',
    demandPercentage: 94,
    growthRate: 148,
    avgSalary: '$145,000',
    openRolesCount: 4280,
    demandTrend: [
      { month: 'Oct', value: 65 },
      { month: 'Nov', value: 74 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 94 },
    ],
  },
  {
    skill: 'Python & FastAPI',
    category: 'Backend Programming',
    demandPercentage: 91,
    growthRate: 42,
    avgSalary: '$130,000',
    openRolesCount: 6120,
    demandTrend: [
      { month: 'Oct', value: 82 },
      { month: 'Nov', value: 85 },
      { month: 'Dec', value: 87 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 91 },
    ],
  },
  {
    skill: 'TypeScript & Next.js 15',
    category: 'Full-Stack Web',
    demandPercentage: 88,
    growthRate: 64,
    avgSalary: '$125,000',
    openRolesCount: 5490,
    demandTrend: [
      { month: 'Oct', value: 76 },
      { month: 'Nov', value: 80 },
      { month: 'Dec', value: 83 },
      { month: 'Jan', value: 86 },
      { month: 'Feb', value: 88 },
    ],
  },
  {
    skill: 'Vector DBs (pgvector / Pinecone)',
    category: 'Database Systems',
    demandPercentage: 86,
    growthRate: 185,
    avgSalary: '$140,000',
    openRolesCount: 3850,
    demandTrend: [
      { month: 'Oct', value: 50 },
      { month: 'Nov', value: 62 },
      { month: 'Dec', value: 73 },
      { month: 'Jan', value: 81 },
      { month: 'Feb', value: 86 },
    ],
  },
  {
    skill: 'Kubernetes & Cloud Native',
    category: 'DevOps & Infra',
    demandPercentage: 85,
    growthRate: 38,
    avgSalary: '$138,000',
    openRolesCount: 4900,
    demandTrend: [
      { month: 'Oct', value: 79 },
      { month: 'Nov', value: 81 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 84 },
      { month: 'Feb', value: 85 },
    ],
  },
];

export const mockPlatformUsers: PlatformUser[] = [
  {
    id: 'usr-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@stanford.edu',
    role: 'student',
    organization: 'Apex Institute of Technology',
    status: 'Active',
    joinedDate: 'Sep 2024',
    activityScore: 98,
  },
  {
    id: 'usr-2',
    name: 'Dr. Radhika Sen',
    email: 'radhika.sen@apexinstitute.edu',
    role: 'institute',
    organization: 'Apex Institute of Technology (Dean)',
    status: 'Active',
    joinedDate: 'Aug 2024',
    activityScore: 92,
  },
  {
    id: 'usr-3',
    name: 'Marcus Vance',
    email: 'marcus.vance@anthropic-partner.io',
    role: 'industry',
    organization: 'Anthropic Labs Partner Network',
    status: 'Active',
    joinedDate: 'Nov 2024',
    activityScore: 95,
  },
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena@skillbridge.ai',
    role: 'admin',
    organization: 'SkillBridge Global Systems',
    status: 'Active',
    joinedDate: 'Jan 2024',
    activityScore: 100,
  },
];

export const mockAchievements: AchievementBadge[] = [
  {
    id: 'ach-first-assessment',
    title: 'First Assessment',
    category: 'Code',
    description: 'Completed your first skill verification challenge on SkillBridge.',
    icon: 'Award',
    xpReward: 10,
    unlocked: true,
    unlockedAt: 'Yesterday',
  },
  {
    id: 'ach-first-project',
    title: 'First Project',
    category: 'Architecture',
    description: 'Shipped a verified production-grade project to your portfolio.',
    icon: 'FolderGit2',
    xpReward: 25,
    unlocked: true,
    unlockedAt: '2 days ago',
  },
  {
    id: 'ach-100-xp',
    title: '100 XP Earned',
    category: 'Code',
    description: 'Accumulated 100+ Builder XP across verified activities.',
    icon: 'Flame',
    xpReward: 15,
    unlocked: true,
    unlockedAt: '3 days ago',
  },
  {
    id: 'ach-500-xp',
    title: '500 XP Earned',
    category: 'Code',
    description: 'Crossed the 500 XP builder milestone with consistent effort.',
    icon: 'Zap',
    xpReward: 50,
    unlocked: true,
    unlockedAt: '1 week ago',
  },
  {
    id: 'ach-github-connected',
    title: 'GitHub Connected',
    category: 'Code',
    description: 'Linked verified GitHub account and synced public repositories.',
    icon: 'Github',
    xpReward: 25,
    unlocked: true,
    unlockedAt: '1 week ago',
  },
  {
    id: 'ach-7-day-streak',
    title: '7 Day Streak',
    category: 'Streak',
    description: 'Built and completed daily verification missions 7 days in a row.',
    icon: 'Sparkles',
    xpReward: 35,
    unlocked: true,
    unlockedAt: 'Today',
  },
  {
    id: 'ach-assessment-master',
    title: 'Assessment Master',
    category: 'Code',
    description: 'Successfully passed 5 or more skill verification challenges.',
    icon: 'Trophy',
    xpReward: 100,
    unlocked: false,
  },
  {
    id: 'ach-backend-specialist',
    title: 'Backend Specialist',
    category: 'Architecture',
    description: 'Mastered REST APIs, Spring Boot, or Microservices challenges.',
    icon: 'Server',
    xpReward: 50,
    unlocked: false,
  },
  {
    id: 'ach-ai-explorer',
    title: 'AI Explorer',
    category: 'Architecture',
    description: 'Completed Machine Learning, Neural Networks, or Prompt Engineering challenges.',
    icon: 'BrainCircuit',
    xpReward: 50,
    unlocked: false,
  },
];

export const mockQuests = [
  // ==================== 1. PROGRAMMING ====================
  {
    id: 'quest-java-foundations',
    title: 'Java Foundations',
    category: 'Backend' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'Core Java syntax, primitive vs reference types, control flow, and memory model.',
    skillsGained: ['Java', 'Memory Model', 'Syntax'],
    completed: true,
    questions: [
      {
        id: 'jf-1',
        question: 'In Java, what is the default value of an uninitialized instance variable of type boolean?',
        options: [
          { id: 'jfo-1', text: 'false', correct: true },
          { id: 'jfo-2', text: 'true', correct: false },
          { id: 'jfo-3', text: 'null', correct: false },
          { id: 'jfo-4', text: '0', correct: false },
        ],
        explanation: 'In Java, instance boolean primitives default to false upon heap allocation.',
      },
      {
        id: 'jf-2',
        question: 'Which memory area in the JVM stores local variables and method execution stack frames?',
        options: [
          { id: 'jfo-21', text: 'JVM Stack', correct: true },
          { id: 'jfo-22', text: 'Heap Space', correct: false },
          { id: 'jfo-23', text: 'Metaspace', correct: false },
          { id: 'jfo-24', text: 'Native Memory', correct: false },
        ],
        explanation: 'Each Java thread has a private JVM stack storing frames with local variables and partial results.',
      },
    ],
  },
  {
    id: 'quest-oop',
    title: 'Object Oriented Programming',
    category: 'Backend' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Polymorphism, encapsulation, dynamic method dispatch, and interface segregation.',
    skillsGained: ['OOP', 'Inheritance', 'Polymorphism'],
    completed: false,
    questions: [
      {
        id: 'oop-1',
        question: 'Which principle states that subtypes must be substitutable for their base types without altering program correctness?',
        options: [
          { id: 'oopo-1', text: 'Liskov Substitution Principle (LSP)', correct: true },
          { id: 'oopo-2', text: 'Single Responsibility Principle', correct: false },
          { id: 'oopo-3', text: 'Open/Closed Principle', correct: false },
          { id: 'oopo-4', text: 'Dependency Inversion Principle', correct: false },
        ],
        explanation: 'Liskov Substitution ensures inheritance hierarchies maintain contractual guarantees.',
      },
      {
        id: 'oop-2',
        question: 'In Java, can an interface contain method implementations in Java 8 and beyond?',
        options: [
          { id: 'oopo-21', text: 'Yes, using default and static methods', correct: true },
          { id: 'oopo-22', text: 'No, interfaces can never contain code bodies', correct: false },
          { id: 'oopo-23', text: 'Only if marked native', correct: false },
        ],
        explanation: 'Java 8 introduced default and static interface methods for backward-compatible evolution.',
      },
    ],
  },
  {
    id: 'quest-dsa-basics',
    title: 'DSA Basics',
    category: 'Problem Solving' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Asymptotic Big-O analysis, binary search, queues, stacks, and hash collision resolution.',
    skillsGained: ['Data Structures', 'Algorithms', 'Time Complexity'],
    completed: false,
    questions: [
      {
        id: 'dsa-1',
        question: 'What is the average time complexity of searching a key in a well-balanced Hash Table with Open Addressing?',
        options: [
          { id: 'dsao-1', text: 'O(1)', correct: true },
          { id: 'dsao-2', text: 'O(log N)', correct: false },
          { id: 'dsao-3', text: 'O(N)', correct: false },
          { id: 'dsao-4', text: 'O(N log N)', correct: false },
        ],
        explanation: 'Average case lookup in a hash table with good hashing and load factor < 0.7 is O(1).',
      },
      {
        id: 'dsa-2',
        question: 'Which data structure is used to implement Breadth-First Search (BFS) in graph traversal?',
        options: [
          { id: 'dsao-21', text: 'Queue (FIFO)', correct: true },
          { id: 'dsao-22', text: 'Stack (LIFO)', correct: false },
          { id: 'dsao-23', text: 'Min-Heap', correct: false },
        ],
        explanation: 'BFS explores neighbor vertices in FIFO order using a Queue.',
      },
    ],
  },
  {
    id: 'quest-advanced-java',
    title: 'Advanced Java',
    category: 'Backend' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 20,
    description: 'Concurrency primitives, Java 21 virtual threads, CompletableFuture, and G1/ZGC garbage collection.',
    skillsGained: ['Java 21', 'Virtual Threads', 'Concurrency', 'JVM Tuning'],
    completed: false,
    questions: [
      {
        id: 'aj-1',
        question: 'How do Java 21 Virtual Threads prevent blocking OS kernel threads during synchronous socket I/O?',
        options: [
          { id: 'ajo-1', text: 'The JVM unmounts the virtual thread from its carrier carrier thread and parks it in memory until I/O unblocks', correct: true },
          { id: 'ajo-2', text: 'Virtual threads allocate separate CPU cores per connection', correct: false },
          { id: 'ajo-3', text: 'They execute asynchronous callbacks compiled to C++', correct: false },
        ],
        explanation: 'Loom virtual threads yield their carrier OS thread on blocking I/O, allowing massive concurrency with synchronous code style.',
      },
    ],
  },

  // ==================== 2. DATABASES ====================
  {
    id: 'quest-sql-fundamentals',
    title: 'SQL Fundamentals',
    category: 'Database' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'SELECT, JOIN, GROUP BY, HAVING, subqueries, and ACID transaction guarantees.',
    skillsGained: ['SQL', 'PostgreSQL', 'Relational Models'],
    completed: true,
    questions: [
      {
        id: 'sqlf-1',
        question: 'Which SQL clause filters grouped rows aggregated by GROUP BY?',
        options: [
          { id: 'sqlo-1', text: 'HAVING', correct: true },
          { id: 'sqlo-2', text: 'WHERE', correct: false },
          { id: 'sqlo-3', text: 'ORDER BY', correct: false },
          { id: 'sqlo-4', text: 'FILTER', correct: false },
        ],
        explanation: 'WHERE filters individual records prior to grouping; HAVING filters aggregated groups.',
      },
    ],
  },
  {
    id: 'quest-db-design',
    title: 'Database Design',
    category: 'Database' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Schema modeling, composite indexes, foreign key cascading, and partition strategies.',
    skillsGained: ['Database Design', 'Schema Modeling', 'Indexing'],
    completed: false,
    questions: [
      {
        id: 'dbd-1',
        question: 'In PostgreSQL, when querying with WHERE status = $1 AND created_at > $2, what composite index order is optimal?',
        options: [
          { id: 'dbdo-1', text: '(status, created_at) — equality column first, range column second', correct: true },
          { id: 'dbdo-2', text: '(created_at, status) — range column first', correct: false },
          { id: 'dbdo-3', text: 'Order does not matter in B-Tree composite keys', correct: false },
        ],
        explanation: 'Placing equality filter columns first allows B-Trees to isolate the exact branch before scanning the range.',
      },
    ],
  },
  {
    id: 'quest-normalization',
    title: 'Normalization Challenge',
    category: 'Database' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 20,
    description: '1NF to BCNF decomposition, eliminating transitive dependencies, and anomaly mitigation.',
    skillsGained: ['Normalization', 'BCNF', '3NF', 'Data Integrity'],
    completed: false,
    questions: [
      {
        id: 'norm-1',
        question: 'A relational table is in Third Normal Form (3NF) if it is in 2NF and has NO:',
        options: [
          { id: 'normo-1', text: 'Transitive dependencies between non-prime attributes and the primary key', correct: true },
          { id: 'normo-2', text: 'Foreign keys to external tables', correct: false },
          { id: 'normo-3', text: 'Composite primary keys', correct: false },
        ],
        explanation: '3NF requires that non-key attributes depend only on the primary key, avoiding transitive dependencies.',
      },
    ],
  },

  // ==================== 3. WEB DEVELOPMENT ====================
  {
    id: 'quest-html-css',
    title: 'HTML & CSS',
    category: 'Frontend' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'Semantic HTML5, Flexbox, CSS Grid, specificity hierarchy, and responsive viewports.',
    skillsGained: ['HTML5', 'CSS3', 'Flexbox', 'Responsive Design'],
    completed: true,
    questions: [
      {
        id: 'hc-1',
        question: 'In CSS Flexbox, which property aligns items along the cross-axis?',
        options: [
          { id: 'hco-1', text: 'align-items', correct: true },
          { id: 'hco-2', text: 'justify-content', correct: false },
          { id: 'hco-3', text: 'flex-direction', correct: false },
        ],
        explanation: 'justify-content aligns along the main axis; align-items aligns along the cross axis.',
      },
    ],
  },
  {
    id: 'quest-js-fundamentals',
    title: 'JavaScript Fundamentals',
    category: 'Frontend' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Event loop, microtasks vs macrotasks, closures, prototypes, and Promises.',
    skillsGained: ['JavaScript', 'Event Loop', 'Closures', 'Async/Await'],
    completed: false,
    questions: [
      {
        id: 'jsf-1',
        question: 'In the JavaScript Event Loop, which queue takes precedence for execution after the current call stack clears?',
        options: [
          { id: 'jsfo-1', text: 'Microtask Queue (Promise.then, queueMicrotask)', correct: true },
          { id: 'jsfo-2', text: 'Macrotask Queue (setTimeout, setInterval)', correct: false },
          { id: 'jsfo-3', text: 'I/O Polling Queue', correct: false },
        ],
        explanation: 'Microtasks run immediately after current script execution and drain completely before the next macrotask executes.',
      },
    ],
  },
  {
    id: 'quest-react-foundations',
    title: 'React Foundations',
    category: 'Frontend' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 20,
    description: 'React Fiber architecture, hooks lifecycle, concurrency mode, and memoization patterns.',
    skillsGained: ['React', 'Hooks', 'Virtual DOM', 'State Management'],
    completed: false,
    questions: [
      {
        id: 'rf-1',
        question: 'Why should useEffect dependencies include all reactive values used inside the effect callback?',
        options: [
          { id: 'rfo-1', text: 'To prevent stale closures capturing outdated state and props across renders', correct: true },
          { id: 'rfo-2', text: 'To ensure the DOM element is deleted and re-created', correct: false },
          { id: 'rfo-3', text: 'React will fail to compile otherwise', correct: false },
        ],
        explanation: 'Omitting variables creates stale closures that read historical values instead of fresh render cycle state.',
      },
    ],
  },

  // ==================== 4. BACKEND ====================
  {
    id: 'quest-rest-apis',
    title: 'REST APIs',
    category: 'Backend' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'HTTP verbs, idempotent semantics, status codes (201, 204, 409), and pagination standards.',
    skillsGained: ['REST', 'HTTP Standards', 'API Design', 'Idempotency'],
    completed: false,
    questions: [
      {
        id: 'rest-1',
        question: 'Which of the following HTTP methods is defined as IDEMPOTENT according to RFC 9110?',
        options: [
          { id: 'resto-1', text: 'PUT and DELETE', correct: true },
          { id: 'resto-2', text: 'POST only', correct: false },
          { id: 'resto-3', text: 'PATCH only', correct: false },
        ],
        explanation: 'Idempotent methods (GET, PUT, DELETE, HEAD) produce the same server state side-effect when executed multiple times.',
      },
    ],
  },
  {
    id: 'quest-spring-boot',
    title: 'Spring Boot',
    category: 'Backend' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 20,
    description: 'Dependency Injection, Spring Bean scopes, Spring Data JPA transactional boundaries, and Actuator.',
    skillsGained: ['Spring Boot', 'JPA', 'Dependency Injection', 'Microservices'],
    completed: false,
    questions: [
      {
        id: 'sb-1',
        question: 'What happens when a method annotated with @Transactional(propagation = Propagation.REQUIRES_NEW) is invoked from another transactional method in Spring?',
        options: [
          { id: 'sbo-1', text: 'The existing transaction is suspended, and a new, independent physical transaction is opened', correct: true },
          { id: 'sbo-2', text: 'An exception is thrown immediately', correct: false },
          { id: 'sbo-3', text: 'The outer transaction rolls back unconditionally', correct: false },
        ],
        explanation: 'REQUIRES_NEW creates an isolated transaction boundary, suspending any current ambient transaction.',
      },
    ],
  },
  {
    id: 'quest-microservices',
    title: 'Microservices',
    category: 'Backend' as const,
    difficulty: 'Expert' as const,
    xpReward: 100,
    estimatedMinutes: 30,
    description: 'Service mesh, gRPC protocol buffers, Saga distributed transactions, and circuit breakers.',
    skillsGained: ['Microservices', 'gRPC', 'Distributed Tracing', 'Saga Pattern'],
    completed: false,
    questions: [
      {
        id: 'ms-1',
        question: 'In a microservice architecture, why is the Outbox Pattern used alongside message brokers like Kafka?',
        options: [
          { id: 'mso-1', text: 'To ensure atomic database updates and event publishing without dual-write inconsistency', correct: true },
          { id: 'mso-2', text: 'To compress JSON payloads into gzip', correct: false },
          { id: 'mso-3', text: 'To bypass network firewalls', correct: false },
        ],
        explanation: 'The Transactional Outbox Pattern writes domain events to an outbox table in the same DB transaction, guaranteeing at-least-once publishing.',
      },
    ],
  },

  // ==================== 5. AI ====================
  {
    id: 'quest-ml-basics',
    title: 'Machine Learning Basics',
    category: 'AI & ML' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Supervised vs unsupervised learning, gradient descent, bias-variance tradeoff, and evaluation metrics.',
    skillsGained: ['Machine Learning', 'Gradient Descent', 'Scikit-Learn'],
    completed: false,
    questions: [
      {
        id: 'ml-1',
        question: 'When evaluating a machine learning model on an imbalanced dataset (e.g. fraud detection with 99.9% negative class), which metric is most meaningful?',
        options: [
          { id: 'mlo-1', text: 'Precision-Recall AUC or F1-Score', correct: true },
          { id: 'mlo-2', text: 'Raw Accuracy', correct: false },
          { id: 'mlo-3', text: 'Mean Squared Error', correct: false },
        ],
        explanation: 'Raw accuracy is deceptive on imbalanced sets since predicting only the majority class gives 99.9% accuracy; PR-AUC captures true minority recovery.',
      },
    ],
  },
  {
    id: 'quest-neural-networks',
    title: 'Neural Networks',
    category: 'AI & ML' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 20,
    description: 'Backpropagation, activation functions (GELU, ReLU), cross-entropy loss, and PyTorch autograd.',
    skillsGained: ['Deep Learning', 'PyTorch', 'Backpropagation', 'Tensors'],
    completed: false,
    questions: [
      {
        id: 'nn-1',
        question: 'Why does the Transformer Self-Attention mechanism scale quadratically O(N^2) with sequence length N?',
        options: [
          { id: 'nno-1', text: 'Because each token computes pairwise dot-product attention scores against all other tokens in the sequence matrix (Q * K^T)', correct: true },
          { id: 'nno-2', text: 'Due to recursive backpropagation loops', correct: false },
          { id: 'nno-3', text: 'Because embeddings are stored in disk swap space', correct: false },
        ],
        explanation: 'Self-attention creates an N x N attention matrix mapping every token to every other token in the sequence.',
      },
    ],
  },
  {
    id: 'quest-prompt-engineering',
    title: 'Prompt Engineering',
    category: 'AI & ML' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Chain of Thought (CoT), Few-Shot prompting, structured JSON schema output, and hallucinations guardrails.',
    skillsGained: ['Prompt Engineering', 'LLMs', 'Few-Shot', 'JSON Schema'],
    completed: false,
    questions: [
      {
        id: 'pe-1',
        question: 'Which technique most effectively forces an LLM to follow complex reasoning paths before reaching an answer?',
        options: [
          { id: 'peo-1', text: 'Chain-of-Thought (CoT) prompting encouraging explicit step-by-step reasoning', correct: true },
          { id: 'peo-2', text: 'Increasing generation temperature to 2.0', correct: false },
          { id: 'peo-3', text: 'Using all-caps formatting in the prompt', correct: false },
        ],
        explanation: 'Chain-of-Thought prompting directs model attention to decompose problems sequentially, substantially reducing hallucination rates.',
      },
    ],
  },

  // ==================== 6. BOSS CHALLENGES ====================
  {
    id: 'quest-boss-rate-limiter',
    title: 'REST API with Distributed Rate Limiter',
    category: 'Backend' as const,
    difficulty: 'Boss' as const,
    isBossChallenge: true,
    xpReward: 250,
    estimatedMinutes: 45,
    portfolioImpact: 'Verified Portfolio Achievement & Recruiter Fast-Track',
    description: 'Architect and deploy an enterprise-grade REST API handling 100k requests/min with sub-millisecond Redis rate limiting, circuit breaking, and structured telemetry.',
    skillsGained: ['Enterprise Architecture', 'Distributed Systems', 'Redis', 'Rate Limiting', 'Circuit Breakers'],
    completed: false,
    questions: [
      {
        id: 'bq1',
        question: 'In a distributed multi-region rate limiter, how do you prevent race conditions when decrementing token buckets concurrently in Redis?',
        codeSnippet: 'local current = redis.call("get", KEYS[1])\nif current and tonumber(current) <= 0 then return 0 end\nredis.call("decr", KEYS[1])\nreturn 1',
        options: [
          { id: 'bo1', text: 'Execute the check-and-decrement logic atomically using Redis Lua Scripts or Redis Functions', correct: true },
          { id: 'bo2', text: 'Send multiple uncoordinated GET and SET requests across standard HTTP', correct: false },
          { id: 'bo3', text: 'Rely solely on client-side sleep timers', correct: false },
        ],
        explanation: 'Redis executes Lua scripts as single atomic operations, preventing race conditions between concurrent requests.',
      },
    ],
  },
  {
    id: 'quest-boss-sharded-db',
    title: 'Sharded Database Architecture',
    category: 'Database' as const,
    difficulty: 'Boss' as const,
    isBossChallenge: true,
    xpReward: 500,
    estimatedMinutes: 60,
    portfolioImpact: 'Elite Architecture Badge & Direct Industry Assessment Bypass',
    description: 'Design a globally partitioned database topology with Two-Phase Commit (2PC), Saga patterns for eventual consistency, and cross-shard query planning.',
    skillsGained: ['Database Sharding', '2PC Protocol', 'Saga Pattern', 'Distributed Transactions'],
    completed: false,
    questions: [
      {
        id: 'bq2',
        question: 'When implementing the Saga Pattern for distributed microservice transactions, how are partial failures resolved?',
        options: [
          { id: 'bo21', text: 'By triggering backward Compensating Transactions to undo completed steps in reverse chronological order', correct: true },
          { id: 'bo22', text: 'By holding database locks indefinitely until human intervention occurs', correct: false },
          { id: 'bo23', text: 'By silently ignoring failed payments or inventory updates', correct: false },
        ],
        explanation: 'The Saga Pattern coordinates a sequence of local transactions where each step publishes events, and failures trigger compensating rollback transactions.',
      },
    ],
  },
];

export const mockLearningPaths = [
  {
    id: 'path-backend',
    title: 'Backend Engineering',
    targetRole: 'Backend Engineer',
    description: 'From OOP & database indexing to high-throughput distributed microservices and Raft consensus.',
    totalSteps: 5,
    completedSteps: 2,
    steps: [
      { id: 'b-1', stepNumber: 1, title: 'Java Foundations & OOP', status: 'completed' as const, xpReward: 10 },
      { id: 'b-2', stepNumber: 2, title: 'PostgreSQL Indexing & B-Trees', status: 'completed' as const, xpReward: 25 },
      { id: 'b-3', stepNumber: 3, title: 'Docker & Multi-Stage Containers', status: 'in_progress' as const, xpReward: 25 },
      { id: 'b-4', stepNumber: 4, title: 'System Design & Rate Limiting', status: 'locked' as const, xpReward: 50 },
      { id: 'b-5', stepNumber: 5, title: 'Distributed Consensus & Raft', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-frontend',
    title: 'Frontend Engineering',
    targetRole: 'Frontend Engineer',
    description: 'Component lifecycles, Virtual DOM diffing, modern state orchestration, and SSR performance.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'f-1', stepNumber: 1, title: 'Modern DOM & State Lifecycle', status: 'completed' as const, xpReward: 10 },
      { id: 'f-2', stepNumber: 2, title: 'TypeScript & Type Narrowing', status: 'in_progress' as const, xpReward: 25 },
      { id: 'f-3', stepNumber: 3, title: 'Next.js Server Components & Turbopack', status: 'locked' as const, xpReward: 50 },
      { id: 'f-4', stepNumber: 4, title: 'Web Vitals & Browser Memory Profiling', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-ai',
    title: 'AI & Machine Learning',
    targetRole: 'AI Engineer',
    description: 'From PyTorch tensors and embeddings to high-throughput inference serving with Triton & vLLM.',
    totalSteps: 4,
    completedSteps: 2,
    steps: [
      { id: 'a-1', stepNumber: 1, title: 'Python & Async Data Pipelines', status: 'completed' as const, xpReward: 10 },
      { id: 'a-2', stepNumber: 2, title: 'PyTorch & Transformer Architectures', status: 'completed' as const, xpReward: 25 },
      { id: 'a-3', stepNumber: 3, title: 'Vector Embeddings & HNSW Indexing', status: 'in_progress' as const, xpReward: 50 },
      { id: 'a-4', stepNumber: 4, title: 'Triton Server & Speculative Decoding', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-data-science',
    title: 'Data Science',
    targetRole: 'Data Scientist',
    description: 'Exploratory data analysis, feature engineering, distributed Spark pipelines, and statistical modeling.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'ds-1', stepNumber: 1, title: 'Statistical Distributions & Hypothesis Testing', status: 'completed' as const, xpReward: 10 },
      { id: 'ds-2', stepNumber: 2, title: 'Pandas & High-Performance Vectorization', status: 'in_progress' as const, xpReward: 25 },
      { id: 'ds-3', stepNumber: 3, title: 'Gradient Boosting & XGBoost Calibration', status: 'locked' as const, xpReward: 50 },
      { id: 'ds-4', stepNumber: 4, title: 'Distributed Apache Spark & Parquet Engines', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-cloud',
    title: 'Cloud Computing',
    targetRole: 'Cloud Architect',
    description: 'Infrastructure as Code (Terraform), multi-region VPC topologies, IAM governance, and Kubernetes.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'c-1', stepNumber: 1, title: 'Cloud Fundamentals & S3 Architecture', status: 'completed' as const, xpReward: 10 },
      { id: 'c-2', stepNumber: 2, title: 'Terraform & Immutable Infrastructure', status: 'in_progress' as const, xpReward: 25 },
      { id: 'c-3', stepNumber: 3, title: 'Kubernetes Pod Scheduling & Ingress', status: 'locked' as const, xpReward: 50 },
      { id: 'c-4', stepNumber: 4, title: 'Multi-Region High-Availability Topologies', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-cybersecurity',
    title: 'Cybersecurity',
    targetRole: 'Security Engineer',
    description: 'Threat modeling, OAuth 2.1 authorization flows, cryptographic signatures, and network intrusion detection.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'cs-1', stepNumber: 1, title: 'Network Protocols & TLS 1.3 Handshake', status: 'completed' as const, xpReward: 10 },
      { id: 'cs-2', stepNumber: 2, title: 'Zero Trust Auth & Token Security', status: 'in_progress' as const, xpReward: 25 },
      { id: 'cs-3', stepNumber: 3, title: 'OWASP Top 10 & Memory Exploits', status: 'locked' as const, xpReward: 50 },
      { id: 'cs-4', stepNumber: 4, title: 'Enterprise Cryptography & Key Rotation', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-problem-solving',
    title: 'Problem Solving & DSA',
    targetRole: 'Algorithm Specialist',
    description: 'Array manipulations, Dynamic Programming, Advanced Graph Theory, and Bitmasking.',
    totalSteps: 4,
    completedSteps: 2,
    steps: [
      { id: 'ps-1', stepNumber: 1, title: 'Two Pointers & Sliding Window', status: 'completed' as const, xpReward: 10 },
      { id: 'ps-2', stepNumber: 2, title: 'Binary Search Trees & Graphs', status: 'completed' as const, xpReward: 25 },
      { id: 'ps-3', stepNumber: 3, title: 'Dynamic Programming & Memoization', status: 'in_progress' as const, xpReward: 50 },
      { id: 'ps-4', stepNumber: 4, title: 'Segment Trees & Disjoint Set Unions', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-aptitude',
    title: 'Aptitude & Logic',
    targetRole: 'All Tracks',
    description: 'Quantitative aptitude, spatial reasoning, data interpretation, and mental agility.',
    totalSteps: 3,
    completedSteps: 1,
    steps: [
      { id: 'ap-1', stepNumber: 1, title: 'Quantitative Logic & Probability', status: 'completed' as const, xpReward: 10 },
      { id: 'ap-2', stepNumber: 2, title: 'Data Interpretation & Chart Analysis', status: 'in_progress' as const, xpReward: 25 },
      { id: 'ap-3', stepNumber: 3, title: 'Abstract Reasoning & Speed Matrices', status: 'locked' as const, xpReward: 50 },
    ],
  },
  {
    id: 'path-communication',
    title: 'Communication & Leadership',
    targetRole: 'All Tracks',
    description: 'Technical design writing, asynchronous RFC authoring, code review etiquette, and executive pitching.',
    totalSteps: 3,
    completedSteps: 1,
    steps: [
      { id: 'cm-1', stepNumber: 1, title: 'Technical RFC Documentation Standards', status: 'completed' as const, xpReward: 10 },
      { id: 'cm-2', stepNumber: 2, title: 'Constructive Code Review Communication', status: 'in_progress' as const, xpReward: 25 },
      { id: 'cm-3', stepNumber: 3, title: 'Executive Engineering Pitch & Strategy', status: 'locked' as const, xpReward: 50 },
    ],
  },
];

export const mockGitHubData = {
  connected: true,
  username: 'aarav-builder',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Building low-latency vector indexing engines and autonomous multi-agent backend systems.',
  publicRepos: 18,
  totalStars: 142,
  followers: 89,
  following: 42,
  languages: [
    { name: 'Python', percentage: 48, color: '#3B82F6' },
    { name: 'TypeScript', percentage: 32, color: '#60A5FA' },
    { name: 'C++', percentage: 12, color: '#F97316' },
    { name: 'SQL & Others', percentage: 8, color: '#22C55E' },
  ],
  pinnedRepos: [
    {
      name: 'vectormind-core',
      description: 'High-throughput HNSW index search serving 40k QPS with sub-15ms p99 latency in C++ and Python.',
      stars: 84,
      forks: 19,
      language: 'C++',
      url: 'https://github.com/aarav-builder/vectormind-core',
      topics: ['vector-search', 'hnsw', 'cpp', 'python-bindings'],
    },
    {
      name: 'smartcampus-edge-guardian',
      description: '1st Place National Hackathon: On-device vision model for institutional energy conservation.',
      stars: 38,
      forks: 9,
      language: 'Python',
      url: 'https://github.com/aarav-builder/smartcampus-edge',
      topics: ['edge-ai', 'pytorch', 'iot', 'fastapi'],
    },
    {
      name: 'distributed-token-bucket',
      description: 'Distributed sliding-window rate limiter with Redis backend and gRPC client bindings.',
      stars: 20,
      forks: 4,
      language: 'TypeScript',
      url: 'https://github.com/aarav-builder/distributed-token-bucket',
      topics: ['rate-limiter', 'redis', 'typescript', 'grpc'],
    },
  ],
  detectedSkills: ['Python', 'FastAPI', 'PyTorch', 'Docker', 'TypeScript', 'PostgreSQL', 'Machine Learning', 'C++'],
  recentCommitsCount: 348,
  streakDays: 7,
};

