import {
  StudentProfile,
  Assessment,
  LeaderboardEntry,
  RoleSkillGapAnalysis,
  RoadmapPhase,
  InternshipOpportunity,
  DepartmentMetric,
  CurriculumAnalysisResult,
  JobRequirement,
  CandidateApplication,
  Assignment,
  SkillDemandMetric,
  PlatformUser
} from '@/types';

export const mockStudentProfile: StudentProfile = {
  id: 'std-98214',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@stanford.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  headline: 'Aspiring AI Systems Engineer | Full-Stack & Distributed Systems Builder',
  targetRole: 'AI Engineer',
  academic: {
    college: 'Apex Institute of Technology & Science',
    department: 'CSE',
    year: '3rd Year',
    semester: '6th Semester',
    cgpa: 9.14,
    studentId: 'AIT-CSE-2023-042',
  },
  professional: {
    githubUrl: 'https://github.com/aarav-sharma-builder',
    linkedinUrl: 'https://linkedin.com/in/aarav-sharma-tech',
    portfolioUrl: 'https://aaravsharma.dev',
    bio: 'Passionate about bridging high-performance backend systems with modern LLM architectures. Contributor to open-source inference pipelines and winner of 3 national collegiate hackathons.',
    totalProjects: 14,
    hackathonWins: 3,
    researchPapers: 1,
    openSourceContributions: 48,
  },
  builderScores: {
    overall: 885,
    execution: 92,
    leadership: 84,
    innovation: 90,
    problemSolving: 94,
    consistency: 82,
  },
  employabilityScore: 91,
  verifiedSkills: [
    {
      id: 'vs-1',
      name: 'Python & FastAPI',
      category: 'Programming',
      level: 'Expert',
      score: 95,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Aug 14, 2025',
      verificationCode: 'SB-PY-95821',
      evidenceCount: 6,
    },
    {
      id: 'vs-2',
      name: 'PyTorch & Transformers',
      category: 'AI & ML',
      level: 'Advanced',
      score: 88,
      verificationSources: ['Project', 'Assessment', 'Certification'],
      verifiedDate: 'Oct 02, 2025',
      verificationCode: 'SB-AI-88301',
      evidenceCount: 4,
    },
    {
      id: 'vs-3',
      name: 'TypeScript & Next.js',
      category: 'Programming',
      level: 'Advanced',
      score: 86,
      verificationSources: ['Project', 'Assessment'],
      verifiedDate: 'Nov 19, 2025',
      verificationCode: 'SB-TS-86102',
      evidenceCount: 5,
    },
    {
      id: 'vs-4',
      name: 'PostgreSQL & pgvector',
      category: 'Database',
      level: 'Advanced',
      score: 89,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Jan 10, 2026',
      verificationCode: 'SB-DB-89412',
      evidenceCount: 3,
    },
    {
      id: 'vs-5',
      name: 'Docker & Kubernetes',
      category: 'DevOps',
      level: 'Intermediate',
      score: 74,
      verificationSources: ['Certification', 'Project'],
      verifiedDate: 'Jan 28, 2026',
      verificationCode: 'SB-DO-74291',
      evidenceCount: 2,
    },
    {
      id: 'vs-6',
      name: 'Distributed Systems & RPC',
      category: 'Programming',
      level: 'Intermediate',
      score: 78,
      verificationSources: ['Assessment', 'Faculty Validation'],
      verifiedDate: 'Feb 15, 2026',
      verificationCode: 'SB-DS-78330',
      evidenceCount: 3,
    },
  ],
  evidences: [
    {
      id: 'ev-1',
      title: 'Real-time Multimodal Vector Retrieval Engine',
      type: 'GitHub Repo',
      url: 'https://github.com/aarav-sharma-builder/vectormind-core',
      description: 'Engineered high-throughput HNSW index search serving 40k QPS with sub-15ms p99 latency in C++ and Python bindings.',
      date: 'Jan 2026',
      impactScore: 96,
      verified: true,
    },
    {
      id: 'ev-2',
      title: 'SmartCampus IoT Edge Guardian (1st Place)',
      type: 'Hackathon Win',
      url: 'https://devpost.com/software/smartcampus-edge',
      description: 'Led a 4-person engineering team to build on-device edge vision models for university energy conservation.',
      date: 'Dec 2025',
      impactScore: 91,
      verified: true,
    },
    {
      id: 'ev-3',
      title: 'Quantization & Sparse Attention in Small Models',
      type: 'Research Paper',
      url: 'https://arxiv.org/abs/sample-quant-2025',
      description: 'Co-authored paper presented at Student AI Symposium benchmarking 4-bit INT quantization loss on Llama architectures.',
      date: 'Nov 2025',
      impactScore: 88,
      verified: true,
    },
    {
      id: 'ev-4',
      title: 'vLLM Kernel Optimization Contribution',
      type: 'Open Source PR',
      url: 'https://github.com/vllm-project/vllm/pull/sample-pr',
      description: 'Merged PR optimizing CUDA memory buffer allocation for batched speculative decoding.',
      date: 'Feb 2026',
      impactScore: 94,
      verified: true,
    },
  ],
};

export const mockRadarData = [
  { subject: 'Programming', A: 95, fullMark: 100, benchmark: 80 },
  { subject: 'System Design', A: 82, fullMark: 100, benchmark: 75 },
  { subject: 'AI / Machine Learning', A: 88, fullMark: 100, benchmark: 70 },
  { subject: 'Cloud & DevOps', A: 76, fullMark: 100, benchmark: 65 },
  { subject: 'Problem Solving', A: 94, fullMark: 100, benchmark: 85 },
  { subject: 'Communication', A: 84, fullMark: 100, benchmark: 78 },
];

export const mockProgressTrend = [
  { month: 'Sep', builderScore: 720, industryReadiness: 68 },
  { month: 'Oct', builderScore: 750, industryReadiness: 73 },
  { month: 'Nov', builderScore: 795, industryReadiness: 79 },
  { month: 'Dec', builderScore: 825, industryReadiness: 83 },
  { month: 'Jan', builderScore: 855, industryReadiness: 87 },
  { month: 'Feb', builderScore: 885, industryReadiness: 91 },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'asm-1',
    title: 'Advanced Python & Concurrency Benchmark',
    category: 'Programming',
    durationMinutes: 45,
    questionsCount: 15,
    difficulty: 'Hard',
    skillsEvaluated: ['AsyncIO', 'GIL', 'Memory Profiling', 'Generators'],
    passingScore: 75,
    completed: true,
    score: 94,
    percentile: 98.4,
    questions: [
      {
        id: 'q1',
        question: 'How does Python\'s asyncio event loop handle CPU-bound vs I/O-bound tasks in modern runtimes?',
        options: [
          'AsyncIO automatically spawns OS threads for heavy math computations',
          'CPU-bound tasks block the event loop unless offloaded to ProcessPoolExecutor or native threads',
          'The GIL switches threads every microsecond regardless of coroutine suspension',
          'AsyncIO uses kernel fibers to bypass Python GIL limitations'
        ],
        correctAnswer: 1,
        explanation: 'AsyncIO is cooperative single-threaded concurrency; CPU-intensive calculations will starve the event loop unless delegated to separate processes or worker threads.'
      },
      {
        id: 'q2',
        question: 'Which method provides zero-copy deserialization of memory buffers in Python?',
        options: ['pickle.loads()', 'json.loads()', 'memoryview() and struct.unpack_from()', 'io.StringIO()'],
        correctAnswer: 2,
        explanation: 'memoryview allows Python code to access the internal data of an object that supports the buffer protocol without copying.'
      }
    ]
  },
  {
    id: 'asm-2',
    title: 'LLM Engineering & Vector Search Architecture',
    category: 'AI',
    durationMinutes: 40,
    questionsCount: 12,
    difficulty: 'Hard',
    skillsEvaluated: ['RAG', 'HNSW Indexing', 'Context Windows', 'Fine-Tuning'],
    passingScore: 70,
    completed: true,
    score: 88,
    percentile: 93.1,
    questions: [
      {
        id: 'q-ai-1',
        question: 'What is the primary advantage of HNSW (Hierarchical Navigable Small World) graphs over IVFFlat for vector retrieval?',
        options: [
          'HNSW requires zero memory indexing overhead',
          'HNSW provides logarithmic search time with superior recall-latency tradeoff without retraining centroids',
          'HNSW executes exclusively on GPU VRAM',
          'IVFFlat always yields higher accuracy at high dimensions'
        ],
        correctAnswer: 1,
        explanation: 'HNSW builds multi-layer graph structures delivering near sub-linear search latency and high recall even without cluster retraining.'
      }
    ]
  },
  {
    id: 'asm-3',
    title: 'Cloud Native & Kubernetes Pod Lifecycle',
    category: 'Cloud',
    durationMinutes: 30,
    questionsCount: 10,
    difficulty: 'Medium',
    skillsEvaluated: ['K8s Probes', 'Ingress', 'Helm', 'CSI Storage'],
    passingScore: 70,
    completed: false,
    questions: [
      {
        id: 'q-cl-1',
        question: 'When should a startupProbe be configured in a Kubernetes pod specification?',
        options: [
          'To continuously check if the app is alive during normal operation',
          'For legacy or slow-starting containers to prevent readiness/liveness probes killing the pod prematurely',
          'To manage persistent volume mounting timeouts',
          'To route external ingress traffic before DNS propagation'
        ],
        correctAnswer: 1,
        explanation: 'startupProbe disables liveness and readiness checks until it succeeds, protecting slow-booting applications from aggressive restarts.'
      }
    ]
  },
  {
    id: 'asm-4',
    title: 'Analytical Aptitude & Quantitative Reasoning',
    category: 'Aptitude',
    durationMinutes: 35,
    questionsCount: 20,
    difficulty: 'Medium',
    skillsEvaluated: ['Data Interpretation', 'Probability', 'Logical Deduction'],
    passingScore: 75,
    completed: true,
    score: 92,
    percentile: 95.8,
  },
  {
    id: 'asm-5',
    title: 'Executive Technical Communication',
    category: 'Communication',
    durationMinutes: 25,
    questionsCount: 10,
    difficulty: 'Easy',
    skillsEvaluated: ['Stakeholder Sync', 'Architecture Diagrams', 'Incident Post-Mortems'],
    passingScore: 70,
    completed: true,
    score: 85,
    percentile: 89.2,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    studentName: 'Devansh Kulkarni',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 942,
    verifiedSkillsCount: 9,
    level: 22,
    xp: 3840,
    badge: 'Elite Vanguard',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 2,
    studentName: 'Priya Nambiar',
    college: 'National Tech University',
    department: 'AIML',
    builderScore: 918,
    verifiedSkillsCount: 8,
    level: 20,
    xp: 3200,
    badge: 'Master Architect',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 3,
    studentName: 'Aarav Sharma (You)',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 885,
    verifiedSkillsCount: 6,
    level: 18,
    xp: 2450,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 4,
    studentName: 'Rohan Mehra',
    college: 'Metropolitan Institute of Science',
    department: 'IT',
    builderScore: 864,
    verifiedSkillsCount: 7,
    level: 16,
    xp: 1980,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 5,
    studentName: 'Ananya Iyer',
    college: 'Southern Institute of Engineering',
    department: 'ECE',
    builderScore: 842,
    verifiedSkillsCount: 5,
    level: 15,
    xp: 1820,
    badge: 'Senior Builder',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
  },
];

export const mockRoleSkillGap: Record<string, RoleSkillGapAnalysis> = {
  'AI Engineer': {
    targetRole: 'AI Engineer',
    matchPercentage: 86,
    totalRequiredSkills: 8,
    matchedSkillsCount: 6,
    missingSkills: ['Kubernetes / Triton Inference Server', 'Graph Neural Networks & DGL'],
    overview: 'Strong foundation in Python, Vector DBs, and LLM orchestration. You are 2 critical infrastructure skills away from 95%+ enterprise alignment.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'PyTorch & Transformers',
        requiredLevel: 'Expert',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 90,
        recommendedCourse: 'Deep Learning Systems Architecture',
      },
      {
        skill: 'pgvector & Vector Databases',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'LLM Orchestration & RAG',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 92,
        recommendedCourse: 'Advanced Agentic Patterns with LangGraph',
      },
      {
        skill: 'Triton Inference Server / vLLM',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 20,
        recommendedCourse: 'High-Throughput Model Serving with vLLM & TensorRT',
      },
      {
        skill: 'Distributed Training (FSDP / DeepSpeed)',
        requiredLevel: 'Intermediate',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 45,
        recommendedCourse: 'Distributed Machine Learning at Scale',
      },
    ],
  },
  'Backend Developer': {
    targetRole: 'Backend Developer',
    matchPercentage: 92,
    totalRequiredSkills: 7,
    matchedSkillsCount: 6,
    missingSkills: ['Kafka / Event-Driven Architecture'],
    overview: 'Exceptional backend capabilities with proven SQL performance, API design, and asynchronous concurrency.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Advanced',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PostgreSQL Optimization',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'Kafka Message Queuing',
        requiredLevel: 'Advanced',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 40,
        recommendedCourse: 'Enterprise Event Streaming with Apache Kafka',
      },
    ],
  },
  'Data Analyst': {
    targetRole: 'Data Analyst',
    matchPercentage: 78,
    totalRequiredSkills: 6,
    matchedSkillsCount: 4,
    missingSkills: ['PowerBI / Tableau', 'Advanced Business Statistics'],
    overview: 'Solid programmatic and SQL foundation; needs dashboarding and executive stakeholder KPI modeling practice.',
    skillGaps: [
      {
        skill: 'SQL Querying',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PowerBI / Tableau',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 15,
        recommendedCourse: 'Executive BI & Dashboards Masterclass',
      },
    ],
  },
};

export const mockRoadmapPhases: RoadmapPhase[] = [
  {
    id: 'phase-1',
    phaseNumber: 1,
    title: 'Foundation',
    description: 'Master core algorithmic problem solving, modern Python 3.12+, and relational database schema design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Advanced Data Structures & Algorithms', provider: 'SkillBridge Core', duration: '6 weeks', completed: true },
      { title: 'High Performance Python & Concurrency', provider: 'SkillBridge Core', duration: '4 weeks', completed: true },
    ],
    projects: [
      { title: 'Concurrent Cache with LRU & TTL Eviction', description: 'Thread-safe in-memory key-value store', techStack: ['Python', 'Threading', 'TCP Sockets'], completed: true },
    ],
    assessments: [
      { title: 'Data Structures Benchmark', category: 'Programming', completed: true },
      { title: 'Quantitative Aptitude Level 1', category: 'Aptitude', completed: true },
    ],
  },
  {
    id: 'phase-2',
    phaseNumber: 2,
    title: 'Core',
    description: 'Deep dive into REST & gRPC API architecture, vector databases (pgvector), and modern microservice design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Production FastAPI & Distributed Systems', provider: 'Coursera Enterprise', duration: '5 weeks', completed: true },
      { title: 'Vector Embeddings & Semantic Search', provider: 'DeepLearning.AI', duration: '3 weeks', completed: true },
    ],
    projects: [
      { title: 'Hybrid Lexical-Vector Search Engine', description: 'Sub-20ms multi-tenant vector retriever on PostgreSQL', techStack: ['FastAPI', 'pgvector', 'Redis'], completed: true },
    ],
    assessments: [
      { title: 'Advanced Python & Concurrency Benchmark', category: 'Programming', completed: true },
    ],
  },
  {
    id: 'phase-3',
    phaseNumber: 3,
    title: 'Advanced',
    description: 'LLM fine-tuning, Quantization (4-bit/8-bit), RAG evaluation metrics (Ragas), and Triton inference pipelines.',
    status: 'in_progress',
    progressPercentage: 65,
    courses: [
      { title: 'LLM Inference Optimization & vLLM Internals', provider: 'SkillBridge Masterclass', duration: '4 weeks', completed: true },
      { title: 'Kubernetes for Machine Learning Workloads', provider: 'Cloud Native Academy', duration: '4 weeks', completed: false },
    ],
    projects: [
      { title: 'Enterprise Document Intelligence with LangGraph', description: 'Autonomous agentic multi-doc synthesis pipeline', techStack: ['FastAPI', 'LangGraph', 'Docker'], completed: true },
      { title: 'Triton Server TensorRT Deployment', description: 'Deploying quantized Mistral-7B at 80 tokens/sec', techStack: ['Triton', 'TensorRT-LLM', 'CUDA'], completed: false },
    ],
    assessments: [
      { title: 'LLM Engineering & Vector Search Architecture', category: 'AI', completed: true },
      { title: 'Cloud Native & Kubernetes Pod Lifecycle', category: 'Cloud', completed: false },
    ],
  },
  {
    id: 'phase-4',
    phaseNumber: 4,
    title: 'Industry Ready',
    description: 'System design capstone, live client simulations, mock technical interviews, and recruiter talent discovery indexing.',
    status: 'locked',
    progressPercentage: 0,
    courses: [
      { title: 'Large Scale Distributed System Design', provider: 'SkillBridge Enterprise', duration: '4 weeks', completed: false },
      { title: 'AI Ethics, Guardrails & SOC2 Compliance', provider: 'Security Institute', duration: '2 weeks', completed: false },
    ],
    projects: [
      { title: 'Full-Scale Enterprise Workforce Intelligence Platform', description: 'Multi-tenant high-availability microservices', techStack: ['Next.js 15', 'FastAPI', 'PostgreSQL', 'K8s'], completed: false },
    ],
    assessments: [
      { title: 'Full Enterprise Architecture Capstone Exam', category: 'Programming', completed: false },
    ],
  },
];

export const mockInternships: InternshipOpportunity[] = [
  {
    id: 'job-101',
    role: 'AI Infrastructure Engineer Intern',
    company: 'Anthropic Labs Partner Network',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    location: 'San Francisco, CA (Hybrid / Remote)',
    type: 'Hybrid',
    stipend: '$7,500 / month',
    duration: '6 Months',
    matchScore: 94,
    requiredSkills: ['Python', 'PyTorch', 'Vector Search', 'FastAPI'],
    postedDate: '2 days ago',
    applied: false,
    applicantsCount: 42,
    description: 'Help architect low-latency inference pipelines and multi-tenant vector indexes for next-generation intelligence tooling.',
  },
  {
    id: 'job-102',
    role: 'Backend Platform Engineer Intern',
    company: 'Stripe Scale Program',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    location: 'New York, NY (On-site)',
    type: 'On-site',
    stipend: '$8,200 / month',
    duration: '3 Months',
    matchScore: 91,
    requiredSkills: ['Python', 'PostgreSQL', 'Distributed Systems', 'Docker'],
    postedDate: '3 days ago',
    applied: true,
    applicantsCount: 118,
    description: 'Work alongside core payments infrastructure teams optimizing high-throughput transaction ledgers and microservices.',
  },
  {
    id: 'job-103',
    role: 'Full-Stack AI Software Intern',
    company: 'Linear Ventures',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    location: 'Remote',
    type: 'Remote',
    stipend: '$6,800 / month',
    duration: '6 Months',
    matchScore: 88,
    requiredSkills: ['TypeScript', 'Next.js', 'FastAPI', 'Tailwind CSS'],
    postedDate: '5 days ago',
    applied: false,
    applicantsCount: 67,
    description: 'Build polished, responsive user interfaces and robust APIs for automated sprint intelligence and code analysis.',
  },
];

// Institute Portal Seed Data
export const mockDepartmentMetrics: DepartmentMetric[] = [
  {
    name: 'CSE',
    totalStudents: 320,
    overallReadiness: 86,
    programming: 91,
    cloud: 78,
    ai: 88,
    devOps: 74,
    dataScience: 82,
  },
  {
    name: 'AIML',
    totalStudents: 180,
    overallReadiness: 89,
    programming: 88,
    cloud: 72,
    ai: 95,
    devOps: 68,
    dataScience: 94,
  },
  {
    name: 'IT',
    totalStudents: 240,
    overallReadiness: 81,
    programming: 84,
    cloud: 85,
    ai: 70,
    devOps: 82,
    dataScience: 75,
  },
  {
    name: 'ECE',
    totalStudents: 210,
    overallReadiness: 72,
    programming: 75,
    cloud: 60,
    ai: 66,
    devOps: 58,
    dataScience: 69,
  },
];

export const mockCurriculumAnalysis: CurriculumAnalysisResult = {
  syllabusTitle: 'B.Tech CSE - 6th Semester Advanced Computing Curriculum (2025-2026)',
  department: 'Computer Science & Engineering',
  semester: '6th Semester',
  industryRelevanceScore: 78,
  totalTopicsAnalyzed: 44,
  modernTopicsCount: 31,
  missingTopics: [
    {
      topic: 'Vector Databases & Embedding Indexing (HNSW / pgvector)',
      importance: 'Critical',
      industryUsagePercentage: 88,
      recommendedModule: 'Module 4: Advanced Data Storage & RAG Systems',
    },
    {
      topic: 'Cloud Native CI/CD & Kubernetes Manifests',
      importance: 'Critical',
      industryUsagePercentage: 92,
      recommendedModule: 'Module 5: Modern DevOps & Container Orchestration',
    },
    {
      topic: 'LLM Fine-Tuning, Quantization & Prompt Optimization',
      importance: 'High',
      industryUsagePercentage: 84,
      recommendedModule: 'Module 3: Contemporary Applied Machine Intelligence',
    },
    {
      topic: 'gRPC & Protocol Buffers for Low-Latency Microservices',
      importance: 'Moderate',
      industryUsagePercentage: 76,
      recommendedModule: 'Module 2: Distributed Systems Communication',
    },
  ],
  outdatedTopics: [
    'SOAP XML Web Services & WSDL Specifications',
    'CORBA Distributed Object Architectures',
    'Legacy JSP / Servlet Form Submissions',
  ],
  suggestedImprovements: [
    'Replace legacy SOAP XML laboratory exercises with OpenAPI 3.1 & FastAPI Async handlers.',
    'Introduce 4 weeks of hands-on containerization labs (Docker Compose + K8s MiniKube).',
    'Integrate vector search laboratory modules using PostgreSQL + pgvector for unstructured retrieval.',
    'Align assessment rubrics with GitHub Builder evidence and automated unit-test grading.',
  ],
  topSkillsCovered: ['Data Structures', 'Operating Systems', 'RDBMS & SQL', 'Computer Networks', 'Intro to ML'],
};

// Industry Portal Seed Data
export const mockJobRequirements: JobRequirement[] = [
  {
    id: 'req-201',
    title: 'AI Systems Engineer (Graduate 2026)',
    department: 'Applied AI',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'Bangalore / Hyderabad (Hybrid)',
    type: 'Full-Time',
    salaryRange: '$85,000 - $115,000',
    minMatchScore: 80,
    requiredSkills: ['Python', 'PyTorch', 'FastAPI', 'pgvector', 'Docker'],
    preferredSkills: ['vLLM', 'Kubernetes', 'LangGraph'],
    activeApplicants: 34,
    createdAt: 'Mar 01, 2026',
    status: 'Active',
  },
  {
    id: 'req-202',
    title: 'Full-Stack SaaS Platform Engineer',
    department: 'Core Product',
    experienceLevel: 'Associate (1-3 yrs)',
    location: 'Remote (US/India)',
    type: 'Full-Time',
    salaryRange: '$90,000 - $125,000',
    minMatchScore: 75,
    requiredSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind CSS'],
    preferredSkills: ['Redis', 'AWS Lambda', 'GraphQL'],
    activeApplicants: 52,
    createdAt: 'Feb 24, 2026',
    status: 'Active',
  },
  {
    id: 'req-203',
    title: 'Cloud Infrastructure & DevOps Intern',
    department: 'Site Reliability',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'San Francisco, CA',
    type: 'Internship',
    salaryRange: '$6,000 / month',
    minMatchScore: 70,
    requiredSkills: ['Docker', 'Kubernetes', 'Linux Internals', 'Python/Go'],
    preferredSkills: ['Terraform', 'Prometheus', 'Grafana'],
    activeApplicants: 19,
    createdAt: 'Feb 28, 2026',
    status: 'Active',
  },
];

export const mockCandidatesPipeline: CandidateApplication[] = [
  {
    id: 'cand-1',
    studentId: 'std-98214',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 885,
    employabilityScore: 91,
    matchScore: 94,
    stage: 'Interview',
    appliedDate: 'Mar 03, 2026',
    topSkills: ['Python', 'FastAPI', 'PyTorch', 'pgvector'],
    githubUrl: 'https://github.com/aarav-sharma-builder',
  },
  {
    id: 'cand-2',
    studentId: 'std-98215',
    name: 'Devansh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 942,
    employabilityScore: 96,
    matchScore: 98,
    stage: 'Selected',
    appliedDate: 'Mar 01, 2026',
    topSkills: ['Python', 'C++', 'CUDA', 'Distributed Systems'],
    githubUrl: 'https://github.com/devansh-k-vanguard',
  },
  {
    id: 'cand-3',
    studentId: 'std-98216',
    name: 'Priya Nambiar',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    college: 'National Tech University',
    department: 'AIML',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 918,
    employabilityScore: 93,
    matchScore: 92,
    stage: 'Assessment',
    appliedDate: 'Mar 04, 2026',
    topSkills: ['PyTorch', 'Transformers', 'FastAPI', 'MLOps'],
    githubUrl: 'https://github.com/priya-nambiar-ai',
  },
  {
    id: 'cand-4',
    studentId: 'std-98217',
    name: 'Rohan Mehra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    college: 'Metropolitan Institute of Science',
    department: 'IT',
    targetRole: 'Full-Stack SaaS Platform Engineer',
    jobId: 'req-202',
    builderScore: 864,
    employabilityScore: 89,
    matchScore: 88,
    stage: 'Shortlisted',
    appliedDate: 'Mar 05, 2026',
    topSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind'],
    githubUrl: 'https://github.com/rohan-mehra-dev',
  },
  {
    id: 'cand-5',
    studentId: 'std-98218',
    name: 'Ananya Iyer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
    college: 'Southern Institute of Engineering',
    department: 'ECE',
    targetRole: 'Cloud Infrastructure & DevOps Intern',
    jobId: 'req-203',
    builderScore: 842,
    employabilityScore: 86,
    matchScore: 85,
    stage: 'Matched',
    appliedDate: 'Mar 06, 2026',
    topSkills: ['Docker', 'Linux', 'Python', 'K8s'],
    githubUrl: 'https://github.com/ananya-iyer-cloud',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-1',
    title: 'High-Throughput Vector Index Benchmark in Python/C++',
    type: 'Coding Test',
    roleTarget: 'AI Systems Engineer',
    duration: '90 mins',
    totalAssigned: 45,
    submissionsCount: 38,
    averageScore: 82.4,
    status: 'Active',
    dueDate: 'Mar 18, 2026',
  },
  {
    id: 'asg-2',
    title: 'Enterprise Multi-Tenant SaaS DB Schema Design',
    type: 'Case Study',
    roleTarget: 'Full-Stack Platform Engineer',
    duration: '2 Days Takehome',
    totalAssigned: 30,
    submissionsCount: 26,
    averageScore: 88.0,
    status: 'Active',
    dueDate: 'Mar 20, 2026',
  },
  {
    id: 'asg-3',
    title: 'Fault-Tolerant K8s Pod Scheduling Simulator',
    type: 'System Design Challenge',
    roleTarget: 'Cloud Infrastructure Intern',
    duration: '120 mins',
    totalAssigned: 22,
    submissionsCount: 19,
    averageScore: 76.5,
    status: 'Active',
    dueDate: 'Mar 22, 2026',
  },
];

// Admin Portal Seed Data
export const mockSkillDemandMetrics: SkillDemandMetric[] = [
  {
    skill: 'LLM Orchestration & RAG',
    category: 'AI / Machine Learning',
    demandPercentage: 94,
    growthRate: 148,
    avgSalary: '$145,000',
    openRolesCount: 4280,
    demandTrend: [
      { month: 'Oct', value: 65 },
      { month: 'Nov', value: 74 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 94 },
    ],
  },
  {
    skill: 'Python & FastAPI',
    category: 'Backend Programming',
    demandPercentage: 91,
    growthRate: 42,
    avgSalary: '$130,000',
    openRolesCount: 6120,
    demandTrend: [
      { month: 'Oct', value: 82 },
      { month: 'Nov', value: 85 },
      { month: 'Dec', value: 87 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 91 },
    ],
  },
  {
    skill: 'TypeScript & Next.js 15',
    category: 'Full-Stack Web',
    demandPercentage: 88,
    growthRate: 64,
    avgSalary: '$125,000',
    openRolesCount: 5490,
    demandTrend: [
      { month: 'Oct', value: 76 },
      { month: 'Nov', value: 80 },
      { month: 'Dec', value: 83 },
      { month: 'Jan', value: 86 },
      { month: 'Feb', value: 88 },
    ],
  },
  {
    skill: 'Vector DBs (pgvector / Pinecone)',
    category: 'Database Systems',
    demandPercentage: 86,
    growthRate: 185,
    avgSalary: '$140,000',
    openRolesCount: 3850,
    demandTrend: [
      { month: 'Oct', value: 50 },
      { month: 'Nov', value: 62 },
      { month: 'Dec', value: 73 },
      { month: 'Jan', value: 81 },
      { month: 'Feb', value: 86 },
    ],
  },
  {
    skill: 'Kubernetes & Cloud Native',
    category: 'DevOps & Infra',
    demandPercentage: 85,
    growthRate: 38,
    avgSalary: '$138,000',
    openRolesCount: 4900,
    demandTrend: [
      { month: 'Oct', value: 79 },
      { month: 'Nov', value: 81 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 84 },
      { month: 'Feb', value: 85 },
    ],
  },
];

export const mockPlatformUsers: PlatformUser[] = [
  {
    id: 'usr-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@stanford.edu',
    role: 'student',
    organization: 'Apex Institute of Technology',
    status: 'Active',
    joinedDate: 'Sep 2024',
    activityScore: 98,
  },
  {
    id: 'usr-2',
    name: 'Dr. Radhika Sen',
    email: 'radhika.sen@apexinstitute.edu',
    role: 'institute',
    organization: 'Apex Institute of Technology (Dean)',
    status: 'Active',
    joinedDate: 'Aug 2024',
    activityScore: 92,
  },
  {
    id: 'usr-3',
    name: 'Marcus Vance',
    email: 'marcus.vance@anthropic-partner.io',
    role: 'industry',
    organization: 'Anthropic Labs Partner Network',
    status: 'Active',
    joinedDate: 'Nov 2024',
    activityScore: 95,
  },
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena@skillbridge.ai',
    role: 'admin',
    organization: 'SkillBridge Global Systems',
    status: 'Active',
    joinedDate: 'Jan 2024',
    activityScore: 100,
  },
];

export const mockAchievements = [
  {
    id: 'ach-1',
    title: 'First Commit',
    category: 'Code',
    description: 'Connected GitHub and verified initial code repository',
    icon: 'GitCommit',
    xpReward: 25,
    unlocked: true,
    unlockedAt: 'Sep 12, 2025',
  },
  {
    id: 'ach-2',
    title: 'Project Builder',
    category: 'Architecture',
    description: 'Uploaded and verified 3+ production capstone projects',
    icon: 'Layers',
    xpReward: 100,
    unlocked: true,
    unlockedAt: 'Oct 28, 2025',
  },
  {
    id: 'ach-3',
    title: 'Hackathon Warrior',
    category: 'Hackathon',
    description: 'Secured 1st place in National AI collegiate hackathon',
    icon: 'Trophy',
    xpReward: 150,
    unlocked: true,
    unlockedAt: 'Dec 15, 2025',
  },
  {
    id: 'ach-4',
    title: 'GitHub Pro',
    category: 'Community',
    description: 'Accumulated 100+ stars across open-source builder repositories',
    icon: 'Star',
    xpReward: 50,
    unlocked: true,
    unlockedAt: 'Jan 10, 2026',
  },
  {
    id: 'ach-5',
    title: 'Consistency Master',
    category: 'Streak',
    description: 'Maintained a 7-day building and assessment streak',
    icon: 'Flame',
    xpReward: 50,
    unlocked: true,
    unlockedAt: 'Feb 02, 2026',
  },
  {
    id: 'ach-6',
    title: 'Backend Specialist',
    category: 'Architecture',
    description: 'Mastered FastAPI, PostgreSQL, and Redis pipeline concurrency',
    icon: 'Server',
    xpReward: 75,
    unlocked: true,
    unlockedAt: 'Feb 20, 2026',
  },
  {
    id: 'ach-7',
    title: 'AI Explorer',
    category: 'Code',
    description: 'Deployed real-time vector search and LLM inference engine',
    icon: 'Cpu',
    xpReward: 100,
    unlocked: true,
    unlockedAt: 'Mar 01, 2026',
  },
  {
    id: 'ach-8',
    title: 'Problem Solver',
    category: 'Code',
    description: 'Passed 5+ advanced skill assessments with score >90%',
    icon: 'CheckCircle2',
    xpReward: 75,
    unlocked: false,
  },
];

export const mockQuests = [
  // 1. Easy Foundations (10 XP)
  {
    id: 'quest-java',
    title: 'Java Foundations & OOP',
    category: 'Backend' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'OOP concepts, memory management, garbage collection, and Java 21 virtual threads.',
    skillsGained: ['Java', 'OOP', 'JVM Internals'],
    completed: true,
    questions: [
      {
        id: 'jq1',
        question: 'What is the primary benefit of Java 21 Virtual Threads (Project Loom)?',
        codeSnippet: 'Thread.ofVirtual().start(() -> { System.out.println("Running on Virtual Thread"); });',
        options: [
          { id: 'o1', text: 'They execute directly on GPU cores', correct: false },
          { id: 'o2', text: 'Lightweight user-mode threads that scale to millions of concurrent tasks with minimal OS overhead', correct: true },
          { id: 'o3', text: 'They eliminate the Java Garbage Collector completely', correct: false },
        ],
        explanation: 'Virtual threads are lightweight threads managed by the JVM rather than the OS, dramatically reducing memory footprint per thread.',
      },
    ],
  },
  {
    id: 'quest-frontend-dom',
    title: 'Modern DOM & State Lifecycle',
    category: 'Frontend' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'DOM reconciliation, React rendering cycles, and event delegation.',
    skillsGained: ['React', 'JavaScript', 'DOM'],
    completed: false,
    questions: [
      {
        id: 'fe1',
        question: 'Why does React require stable keys when rendering dynamic lists?',
        codeSnippet: 'items.map((item) => <ListItem key={item.id} data={item} />)',
        options: [
          { id: 'feo1', text: 'Keys ensure CSS styles are compiled faster', correct: false },
          { id: 'feo2', text: 'Keys allow React virtual DOM diffing to identify which items have changed, been added, or removed', correct: true },
          { id: 'feo3', text: 'Keys encrypt item payloads across HTTP requests', correct: false },
        ],
        explanation: 'Stable unique keys allow React reconciliation to track identity across renders without destroying and remounting DOM elements unnecessarily.',
      },
    ],
  },
  {
    id: 'quest-aptitude-logic',
    title: 'Quantitative Logic & Probability',
    category: 'Aptitude' as const,
    difficulty: 'Easy' as const,
    xpReward: 10,
    estimatedMinutes: 10,
    description: 'Bayesian probability, permutations, combinations, and logical deduction.',
    skillsGained: ['Probability', 'Quantitative Aptitude', 'Logic'],
    completed: false,
    questions: [
      {
        id: 'ap1',
        question: 'If two fair 6-sided dice are rolled simultaneously, what is the probability that their sum is 7?',
        options: [
          { id: 'apo1', text: '1/6 (6 outcomes out of 36)', correct: true },
          { id: 'apo2', text: '1/12', correct: false },
          { id: 'apo3', text: '7/36', correct: false },
        ],
        explanation: 'The pairs summing to 7 are (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) — exactly 6 out of 36 total outcomes = 1/6.',
      },
    ],
  },

  // 2. Medium Intermediate (25 XP)
  {
    id: 'quest-docker',
    title: 'Docker & Multi-Stage Containers',
    category: 'DevOps' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'Multi-stage builds, container isolation, layer caching, and networking.',
    skillsGained: ['Docker', 'Containers', 'DevOps'],
    completed: false,
    questions: [
      {
        id: 'dq1',
        question: 'Why are multi-stage Docker builds recommended for production images?',
        codeSnippet: 'FROM golang:1.22 AS builder\nWORKDIR /app\nRUN go build -o server\n\nFROM gcr.io/distroless/base\nCOPY --from=builder /app/server /server\nCMD ["/server"]',
        options: [
          { id: 'do1', text: 'They increase container startup time', correct: false },
          { id: 'do2', text: 'They drastically reduce final image size and attack surface by excluding build toolchains', correct: true },
          { id: 'do3', text: 'They automatically bypass firewall port rules', correct: false },
        ],
        explanation: 'Multi-stage builds separate the build environment from the final runtime image, leaving compilers and debuggers out of production.',
      },
    ],
  },
  {
    id: 'quest-sql-index',
    title: 'PostgreSQL Indexing & B-Trees',
    category: 'Database' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 15,
    description: 'B-tree vs GIN indexes, query execution plans, and composite key optimization.',
    skillsGained: ['PostgreSQL', 'SQL', 'Index Optimization'],
    completed: true,
    questions: [
      {
        id: 'sql1',
        question: 'When is a Generalized Inverted Index (GIN) preferred over standard B-Tree index in PostgreSQL?',
        options: [
          { id: 'sqlo1', text: 'For indexing composite array fields, JSONB documents, and full-text search tokens', correct: true },
          { id: 'sqlo2', text: 'For single auto-incrementing integer primary keys', correct: false },
          { id: 'sqlo3', text: 'GIN indexes use 0 disk memory', correct: false },
        ],
        explanation: 'GIN indexes store mapping of element values to item pointers, making them ideal for multi-element columns like JSONB and arrays.',
      },
    ],
  },
  {
    id: 'quest-dsa-trees',
    title: 'Binary Search Trees & Graphs',
    category: 'Problem Solving' as const,
    difficulty: 'Medium' as const,
    xpReward: 25,
    estimatedMinutes: 20,
    description: 'Tree traversals, Dijkstra shortest path, BFS/DFS, and topological sorting.',
    skillsGained: ['Graph Algorithms', 'Trees', 'DSA'],
    completed: false,
    questions: [
      {
        id: 'dsa1',
        question: 'What is the time complexity of Dijkstra algorithm implemented with a Min-Heap priority queue?',
        options: [
          { id: 'dsao1', text: 'O((V + E) log V)', correct: true },
          { id: 'dsao2', text: 'O(V^3)', correct: false },
          { id: 'dsao3', text: 'O(E^2)', correct: false },
        ],
        explanation: 'With a min-heap, each vertex extraction takes O(log V) and each edge relaxation takes O(log V), yielding O((V + E) log V).',
      },
    ],
  },

  // 3. Advanced Industry (50 XP)
  {
    id: 'quest-sysdesign',
    title: 'System Design & Distributed Rate Limiting',
    category: 'Systems' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 25,
    description: 'Distributed sliding window rate limiters, CAP theorem, consistent hashing, and database sharding.',
    skillsGained: ['System Design', 'Distributed Systems', 'Scalability'],
    completed: false,
    questions: [
      {
        id: 'sq1',
        question: 'Which algorithm is best suited for low-memory distributed rate limiting across edge clusters?',
        options: [
          { id: 'so1', text: 'Sliding Window Counter with Redis Sorted Sets or Leaky Bucket', correct: true },
          { id: 'so2', text: 'Full database table lock on every request', correct: false },
          { id: 'so3', text: 'Round Robin DNS routing only', correct: false },
        ],
        explanation: 'Sliding window counter provides smooth rate limiting without the edge spike vulnerabilities of fixed window algorithms.',
      },
    ],
  },
  {
    id: 'quest-ai-embeddings',
    title: 'Vector Embeddings & HNSW Indexing',
    category: 'AI & ML' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 25,
    description: 'Hierarchical Navigable Small World graphs, cosine similarity, and approximate nearest neighbors.',
    skillsGained: ['Vector Search', 'HNSW', 'Embeddings', 'PyTorch'],
    completed: false,
    questions: [
      {
        id: 'ai1',
        question: 'How does HNSW achieve logarithmic time complexity for nearest-neighbor search in high dimensions?',
        options: [
          { id: 'aio1', text: 'By constructing multi-layered graphs with probabilistic skip-list hierarchy of long-distance and short-distance edges', correct: true },
          { id: 'aio2', text: 'By performing exhaustive brute force L2 distance calculations across all nodes', correct: false },
          { id: 'aio3', text: 'By compressing all vectors into 1-bit booleans without graph connections', correct: false },
        ],
        explanation: 'HNSW maintains multiple layers of graphs where top layers have sparse long-range connections for fast skipping and bottom layers refine accuracy.',
      },
    ],
  },
  {
    id: 'quest-cybersecurity-jwt',
    title: 'Zero Trust Auth & Token Security',
    category: 'Cybersecurity' as const,
    difficulty: 'Advanced' as const,
    xpReward: 50,
    estimatedMinutes: 25,
    description: 'JWT signature verification, RSA vs Ed25519, replay attack mitigation, and CSRF protection.',
    skillsGained: ['Zero Trust', 'JWT', 'Cryptographic Signatures'],
    completed: false,
    questions: [
      {
        id: 'sec1',
        question: 'Why should sensitive session JWT tokens be stored in httpOnly, SameSite=Strict cookies rather than localStorage?',
        options: [
          { id: 'seco1', text: 'httpOnly cookies cannot be accessed by malicious JavaScript, mitigating XSS token theft', correct: true },
          { id: 'seco2', text: 'localStorage is limited to 10 bytes of storage', correct: false },
          { id: 'seco3', text: 'httpOnly cookies automatically disable TLS encryption', correct: false },
        ],
        explanation: 'Storing authentication tokens in httpOnly cookies prevents Cross-Site Scripting (XSS) scripts from exfiltrating credentials from the browser.',
      },
    ],
  },

  // 4. Expert Real-World (100 XP)
  {
    id: 'quest-consensus',
    title: 'Distributed Consensus & Raft Protocol',
    category: 'Systems' as const,
    difficulty: 'Expert' as const,
    xpReward: 100,
    estimatedMinutes: 30,
    description: 'Leader election, log replication, split brain prevention, and atomic commits.',
    skillsGained: ['Raft', 'Consensus', 'Fault Tolerance'],
    completed: false,
    questions: [
      {
        id: 'cq1',
        question: 'How does Raft resolve leader election split votes?',
        options: [
          { id: 'co1', text: 'Randomized election timeouts for candidate nodes', correct: true },
          { id: 'co2', text: 'Electing the node with the highest IP address unconditionally', correct: false },
          { id: 'co3', text: 'Pausing all network traffic for 60 seconds', correct: false },
        ],
        explanation: 'Randomized election timeouts ensure nodes start elections at different times, avoiding split votes in quorum elections.',
      },
    ],
  },

  // 5. Boss Challenges (250 & 500 XP)
  {
    id: 'quest-boss-rest-api',
    title: 'Boss Challenge: High-Throughput REST API with Distributed Token Bucket',
    category: 'Backend' as const,
    difficulty: 'Boss' as const,
    isBossChallenge: true,
    xpReward: 250,
    estimatedMinutes: 45,
    portfolioImpact: 'Verified Portfolio Achievement & Recruiter Fast-Track',
    description: 'Architect and deploy an enterprise-grade REST API handling 100k requests/min with sub-millisecond Redis rate limiting, circuit breaking, and structured telemetry.',
    skillsGained: ['Enterprise Architecture', 'Distributed Systems', 'Redis', 'Rate Limiting', 'Circuit Breakers'],
    completed: false,
    questions: [
      {
        id: 'bq1',
        question: 'In a distributed multi-region rate limiter, how do you prevent race conditions when decrementing token buckets concurrently in Redis?',
        codeSnippet: 'local current = redis.call("get", KEYS[1])\nif current and tonumber(current) <= 0 then return 0 end\nredis.call("decr", KEYS[1])\nreturn 1',
        options: [
          { id: 'bo1', text: 'Execute the check-and-decrement logic atomically using Redis Lua Scripts or Redis Functions', correct: true },
          { id: 'bo2', text: 'Send multiple uncoordinated GET and SET requests across standard HTTP', correct: false },
          { id: 'bo3', text: 'Rely solely on client-side sleep timers', correct: false },
        ],
        explanation: 'Redis executes Lua scripts as single atomic operations, preventing race conditions between concurrent requests.',
      },
    ],
  },
  {
    id: 'quest-boss-database-sharding',
    title: 'Boss Challenge: Sharded Database Architecture & Distributed Transactions',
    category: 'Database' as const,
    difficulty: 'Boss' as const,
    isBossChallenge: true,
    xpReward: 500,
    estimatedMinutes: 60,
    portfolioImpact: 'Elite Architecture Badge & Direct Industry Assessment Bypass',
    description: 'Design a globally partitioned database topology with Two-Phase Commit (2PC), Saga patterns for eventual consistency, and cross-shard query planning.',
    skillsGained: ['Database Sharding', '2PC Protocol', 'Saga Pattern', 'Distributed Transactions'],
    completed: false,
    questions: [
      {
        id: 'bq2',
        question: 'When implementing the Saga Pattern for distributed microservice transactions, how are partial failures resolved?',
        options: [
          { id: 'bo21', text: 'By triggering backward Compensating Transactions to undo completed steps in reverse chronological order', correct: true },
          { id: 'bo22', text: 'By holding database locks indefinitely until human intervention occurs', correct: false },
          { id: 'bo23', text: 'By silently ignoring failed payments or inventory updates', correct: false },
        ],
        explanation: 'The Saga Pattern coordinates a sequence of local transactions where each step publishes events, and failures trigger compensating rollback transactions.',
      },
    ],
  },
];

export const mockLearningPaths = [
  {
    id: 'path-backend',
    title: 'Backend Engineering',
    targetRole: 'Backend Engineer',
    description: 'From OOP & database indexing to high-throughput distributed microservices and Raft consensus.',
    totalSteps: 5,
    completedSteps: 2,
    steps: [
      { id: 'b-1', stepNumber: 1, title: 'Java Foundations & OOP', status: 'completed' as const, xpReward: 10 },
      { id: 'b-2', stepNumber: 2, title: 'PostgreSQL Indexing & B-Trees', status: 'completed' as const, xpReward: 25 },
      { id: 'b-3', stepNumber: 3, title: 'Docker & Multi-Stage Containers', status: 'in_progress' as const, xpReward: 25 },
      { id: 'b-4', stepNumber: 4, title: 'System Design & Rate Limiting', status: 'locked' as const, xpReward: 50 },
      { id: 'b-5', stepNumber: 5, title: 'Distributed Consensus & Raft', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-frontend',
    title: 'Frontend Engineering',
    targetRole: 'Frontend Engineer',
    description: 'Component lifecycles, Virtual DOM diffing, modern state orchestration, and SSR performance.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'f-1', stepNumber: 1, title: 'Modern DOM & State Lifecycle', status: 'completed' as const, xpReward: 10 },
      { id: 'f-2', stepNumber: 2, title: 'TypeScript & Type Narrowing', status: 'in_progress' as const, xpReward: 25 },
      { id: 'f-3', stepNumber: 3, title: 'Next.js Server Components & Turbopack', status: 'locked' as const, xpReward: 50 },
      { id: 'f-4', stepNumber: 4, title: 'Web Vitals & Browser Memory Profiling', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-ai',
    title: 'AI & Machine Learning',
    targetRole: 'AI Engineer',
    description: 'From PyTorch tensors and embeddings to high-throughput inference serving with Triton & vLLM.',
    totalSteps: 4,
    completedSteps: 2,
    steps: [
      { id: 'a-1', stepNumber: 1, title: 'Python & Async Data Pipelines', status: 'completed' as const, xpReward: 10 },
      { id: 'a-2', stepNumber: 2, title: 'PyTorch & Transformer Architectures', status: 'completed' as const, xpReward: 25 },
      { id: 'a-3', stepNumber: 3, title: 'Vector Embeddings & HNSW Indexing', status: 'in_progress' as const, xpReward: 50 },
      { id: 'a-4', stepNumber: 4, title: 'Triton Server & Speculative Decoding', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-data-science',
    title: 'Data Science',
    targetRole: 'Data Scientist',
    description: 'Exploratory data analysis, feature engineering, distributed Spark pipelines, and statistical modeling.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'ds-1', stepNumber: 1, title: 'Statistical Distributions & Hypothesis Testing', status: 'completed' as const, xpReward: 10 },
      { id: 'ds-2', stepNumber: 2, title: 'Pandas & High-Performance Vectorization', status: 'in_progress' as const, xpReward: 25 },
      { id: 'ds-3', stepNumber: 3, title: 'Gradient Boosting & XGBoost Calibration', status: 'locked' as const, xpReward: 50 },
      { id: 'ds-4', stepNumber: 4, title: 'Distributed Apache Spark & Parquet Engines', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-cloud',
    title: 'Cloud Computing',
    targetRole: 'Cloud Architect',
    description: 'Infrastructure as Code (Terraform), multi-region VPC topologies, IAM governance, and Kubernetes.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'c-1', stepNumber: 1, title: 'Cloud Fundamentals & S3 Architecture', status: 'completed' as const, xpReward: 10 },
      { id: 'c-2', stepNumber: 2, title: 'Terraform & Immutable Infrastructure', status: 'in_progress' as const, xpReward: 25 },
      { id: 'c-3', stepNumber: 3, title: 'Kubernetes Pod Scheduling & Ingress', status: 'locked' as const, xpReward: 50 },
      { id: 'c-4', stepNumber: 4, title: 'Multi-Region High-Availability Topologies', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-cybersecurity',
    title: 'Cybersecurity',
    targetRole: 'Security Engineer',
    description: 'Threat modeling, OAuth 2.1 authorization flows, cryptographic signatures, and network intrusion detection.',
    totalSteps: 4,
    completedSteps: 1,
    steps: [
      { id: 'cs-1', stepNumber: 1, title: 'Network Protocols & TLS 1.3 Handshake', status: 'completed' as const, xpReward: 10 },
      { id: 'cs-2', stepNumber: 2, title: 'Zero Trust Auth & Token Security', status: 'in_progress' as const, xpReward: 25 },
      { id: 'cs-3', stepNumber: 3, title: 'OWASP Top 10 & Memory Exploits', status: 'locked' as const, xpReward: 50 },
      { id: 'cs-4', stepNumber: 4, title: 'Enterprise Cryptography & Key Rotation', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-problem-solving',
    title: 'Problem Solving & DSA',
    targetRole: 'Algorithm Specialist',
    description: 'Array manipulations, Dynamic Programming, Advanced Graph Theory, and Bitmasking.',
    totalSteps: 4,
    completedSteps: 2,
    steps: [
      { id: 'ps-1', stepNumber: 1, title: 'Two Pointers & Sliding Window', status: 'completed' as const, xpReward: 10 },
      { id: 'ps-2', stepNumber: 2, title: 'Binary Search Trees & Graphs', status: 'completed' as const, xpReward: 25 },
      { id: 'ps-3', stepNumber: 3, title: 'Dynamic Programming & Memoization', status: 'in_progress' as const, xpReward: 50 },
      { id: 'ps-4', stepNumber: 4, title: 'Segment Trees & Disjoint Set Unions', status: 'locked' as const, xpReward: 100 },
    ],
  },
  {
    id: 'path-aptitude',
    title: 'Aptitude & Logic',
    targetRole: 'All Tracks',
    description: 'Quantitative aptitude, spatial reasoning, data interpretation, and mental agility.',
    totalSteps: 3,
    completedSteps: 1,
    steps: [
      { id: 'ap-1', stepNumber: 1, title: 'Quantitative Logic & Probability', status: 'completed' as const, xpReward: 10 },
      { id: 'ap-2', stepNumber: 2, title: 'Data Interpretation & Chart Analysis', status: 'in_progress' as const, xpReward: 25 },
      { id: 'ap-3', stepNumber: 3, title: 'Abstract Reasoning & Speed Matrices', status: 'locked' as const, xpReward: 50 },
    ],
  },
  {
    id: 'path-communication',
    title: 'Communication & Leadership',
    targetRole: 'All Tracks',
    description: 'Technical design writing, asynchronous RFC authoring, code review etiquette, and executive pitching.',
    totalSteps: 3,
    completedSteps: 1,
    steps: [
      { id: 'cm-1', stepNumber: 1, title: 'Technical RFC Documentation Standards', status: 'completed' as const, xpReward: 10 },
      { id: 'cm-2', stepNumber: 2, title: 'Constructive Code Review Communication', status: 'in_progress' as const, xpReward: 25 },
      { id: 'cm-3', stepNumber: 3, title: 'Executive Engineering Pitch & Strategy', status: 'locked' as const, xpReward: 50 },
    ],
  },
];

export const mockGitHubData = {
  connected: true,
  username: 'aarav-builder',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Building low-latency vector indexing engines and autonomous multi-agent backend systems.',
  publicRepos: 18,
  totalStars: 142,
  followers: 89,
  following: 42,
  languages: [
    { name: 'Python', percentage: 48, color: '#3B82F6' },
    { name: 'TypeScript', percentage: 32, color: '#60A5FA' },
    { name: 'C++', percentage: 12, color: '#F97316' },
    { name: 'SQL & Others', percentage: 8, color: '#22C55E' },
  ],
  pinnedRepos: [
    {
      name: 'vectormind-core',
      description: 'High-throughput HNSW index search serving 40k QPS with sub-15ms p99 latency in C++ and Python.',
      stars: 84,
      forks: 19,
      language: 'C++',
      url: 'https://github.com/aarav-builder/vectormind-core',
      topics: ['vector-search', 'hnsw', 'cpp', 'python-bindings'],
    },
    {
      name: 'smartcampus-edge-guardian',
      description: '1st Place National Hackathon: On-device vision model for institutional energy conservation.',
      stars: 38,
      forks: 9,
      language: 'Python',
      url: 'https://github.com/aarav-builder/smartcampus-edge',
      topics: ['edge-ai', 'pytorch', 'iot', 'fastapi'],
    },
    {
      name: 'distributed-token-bucket',
      description: 'Distributed sliding-window rate limiter with Redis backend and gRPC client bindings.',
      stars: 20,
      forks: 4,
      language: 'TypeScript',
      url: 'https://github.com/aarav-builder/distributed-token-bucket',
      topics: ['rate-limiter', 'redis', 'typescript', 'grpc'],
    },
  ],
  detectedSkills: ['Python', 'FastAPI', 'PyTorch', 'Docker', 'TypeScript', 'PostgreSQL', 'Machine Learning', 'C++'],
  recentCommitsCount: 348,
  streakDays: 7,
};

