import {
  StudentProfile,
  Assessment,
  LeaderboardEntry,
  RoleSkillGapAnalysis,
  RoadmapPhase,
  InternshipOpportunity,
  DepartmentMetric,
  CurriculumAnalysisResult,
  JobRequirement,
  CandidateApplication,
  Assignment,
  SkillDemandMetric,
  PlatformUser
} from '@/types';

export const mockStudentProfile: StudentProfile = {
  id: 'std-98214',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@stanford.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  headline: 'Aspiring AI Systems Engineer | Full-Stack & Distributed Systems Builder',
  targetRole: 'AI Engineer',
  academic: {
    college: 'Apex Institute of Technology & Science',
    department: 'CSE',
    year: '3rd Year',
    semester: '6th Semester',
    cgpa: 9.14,
    studentId: 'AIT-CSE-2023-042',
  },
  professional: {
    githubUrl: 'https://github.com/aarav-sharma-builder',
    linkedinUrl: 'https://linkedin.com/in/aarav-sharma-tech',
    portfolioUrl: 'https://aaravsharma.dev',
    bio: 'Passionate about bridging high-performance backend systems with modern LLM architectures. Contributor to open-source inference pipelines and winner of 3 national collegiate hackathons.',
    totalProjects: 14,
    hackathonWins: 3,
    researchPapers: 1,
    openSourceContributions: 48,
  },
  builderScores: {
    overall: 885,
    execution: 92,
    leadership: 84,
    innovation: 90,
    problemSolving: 94,
    consistency: 82,
  },
  employabilityScore: 91,
  verifiedSkills: [
    {
      id: 'vs-1',
      name: 'Python & FastAPI',
      category: 'Programming',
      level: 'Expert',
      score: 95,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Aug 14, 2025',
      verificationCode: 'SB-PY-95821',
      evidenceCount: 6,
    },
    {
      id: 'vs-2',
      name: 'PyTorch & Transformers',
      category: 'AI & ML',
      level: 'Advanced',
      score: 88,
      verificationSources: ['Project', 'Assessment', 'Certification'],
      verifiedDate: 'Oct 02, 2025',
      verificationCode: 'SB-AI-88301',
      evidenceCount: 4,
    },
    {
      id: 'vs-3',
      name: 'TypeScript & Next.js',
      category: 'Programming',
      level: 'Advanced',
      score: 86,
      verificationSources: ['Project', 'Assessment'],
      verifiedDate: 'Nov 19, 2025',
      verificationCode: 'SB-TS-86102',
      evidenceCount: 5,
    },
    {
      id: 'vs-4',
      name: 'PostgreSQL & pgvector',
      category: 'Database',
      level: 'Advanced',
      score: 89,
      verificationSources: ['Assessment', 'Project', 'Faculty Validation'],
      verifiedDate: 'Jan 10, 2026',
      verificationCode: 'SB-DB-89412',
      evidenceCount: 3,
    },
    {
      id: 'vs-5',
      name: 'Docker & Kubernetes',
      category: 'DevOps',
      level: 'Intermediate',
      score: 74,
      verificationSources: ['Certification', 'Project'],
      verifiedDate: 'Jan 28, 2026',
      verificationCode: 'SB-DO-74291',
      evidenceCount: 2,
    },
    {
      id: 'vs-6',
      name: 'Distributed Systems & RPC',
      category: 'Programming',
      level: 'Intermediate',
      score: 78,
      verificationSources: ['Assessment', 'Faculty Validation'],
      verifiedDate: 'Feb 15, 2026',
      verificationCode: 'SB-DS-78330',
      evidenceCount: 3,
    },
  ],
  evidences: [
    {
      id: 'ev-1',
      title: 'Real-time Multimodal Vector Retrieval Engine',
      type: 'GitHub Repo',
      url: 'https://github.com/aarav-sharma-builder/vectormind-core',
      description: 'Engineered high-throughput HNSW index search serving 40k QPS with sub-15ms p99 latency in C++ and Python bindings.',
      date: 'Jan 2026',
      impactScore: 96,
      verified: true,
    },
    {
      id: 'ev-2',
      title: 'SmartCampus IoT Edge Guardian (1st Place)',
      type: 'Hackathon Win',
      url: 'https://devpost.com/software/smartcampus-edge',
      description: 'Led a 4-person engineering team to build on-device edge vision models for university energy conservation.',
      date: 'Dec 2025',
      impactScore: 91,
      verified: true,
    },
    {
      id: 'ev-3',
      title: 'Quantization & Sparse Attention in Small Models',
      type: 'Research Paper',
      url: 'https://arxiv.org/abs/sample-quant-2025',
      description: 'Co-authored paper presented at Student AI Symposium benchmarking 4-bit INT quantization loss on Llama architectures.',
      date: 'Nov 2025',
      impactScore: 88,
      verified: true,
    },
    {
      id: 'ev-4',
      title: 'vLLM Kernel Optimization Contribution',
      type: 'Open Source PR',
      url: 'https://github.com/vllm-project/vllm/pull/sample-pr',
      description: 'Merged PR optimizing CUDA memory buffer allocation for batched speculative decoding.',
      date: 'Feb 2026',
      impactScore: 94,
      verified: true,
    },
  ],
};

export const mockRadarData = [
  { subject: 'Programming', A: 95, fullMark: 100, benchmark: 80 },
  { subject: 'System Design', A: 82, fullMark: 100, benchmark: 75 },
  { subject: 'AI / Machine Learning', A: 88, fullMark: 100, benchmark: 70 },
  { subject: 'Cloud & DevOps', A: 76, fullMark: 100, benchmark: 65 },
  { subject: 'Problem Solving', A: 94, fullMark: 100, benchmark: 85 },
  { subject: 'Communication', A: 84, fullMark: 100, benchmark: 78 },
];

export const mockProgressTrend = [
  { month: 'Sep', builderScore: 720, industryReadiness: 68 },
  { month: 'Oct', builderScore: 750, industryReadiness: 73 },
  { month: 'Nov', builderScore: 795, industryReadiness: 79 },
  { month: 'Dec', builderScore: 825, industryReadiness: 83 },
  { month: 'Jan', builderScore: 855, industryReadiness: 87 },
  { month: 'Feb', builderScore: 885, industryReadiness: 91 },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'asm-1',
    title: 'Advanced Python & Concurrency Benchmark',
    category: 'Programming',
    durationMinutes: 45,
    questionsCount: 15,
    difficulty: 'Hard',
    skillsEvaluated: ['AsyncIO', 'GIL', 'Memory Profiling', 'Generators'],
    passingScore: 75,
    completed: true,
    score: 94,
    percentile: 98.4,
    questions: [
      {
        id: 'q1',
        question: 'How does Python\'s asyncio event loop handle CPU-bound vs I/O-bound tasks in modern runtimes?',
        options: [
          'AsyncIO automatically spawns OS threads for heavy math computations',
          'CPU-bound tasks block the event loop unless offloaded to ProcessPoolExecutor or native threads',
          'The GIL switches threads every microsecond regardless of coroutine suspension',
          'AsyncIO uses kernel fibers to bypass Python GIL limitations'
        ],
        correctAnswer: 1,
        explanation: 'AsyncIO is cooperative single-threaded concurrency; CPU-intensive calculations will starve the event loop unless delegated to separate processes or worker threads.'
      },
      {
        id: 'q2',
        question: 'Which method provides zero-copy deserialization of memory buffers in Python?',
        options: ['pickle.loads()', 'json.loads()', 'memoryview() and struct.unpack_from()', 'io.StringIO()'],
        correctAnswer: 2,
        explanation: 'memoryview allows Python code to access the internal data of an object that supports the buffer protocol without copying.'
      }
    ]
  },
  {
    id: 'asm-2',
    title: 'LLM Engineering & Vector Search Architecture',
    category: 'AI',
    durationMinutes: 40,
    questionsCount: 12,
    difficulty: 'Hard',
    skillsEvaluated: ['RAG', 'HNSW Indexing', 'Context Windows', 'Fine-Tuning'],
    passingScore: 70,
    completed: true,
    score: 88,
    percentile: 93.1,
    questions: [
      {
        id: 'q-ai-1',
        question: 'What is the primary advantage of HNSW (Hierarchical Navigable Small World) graphs over IVFFlat for vector retrieval?',
        options: [
          'HNSW requires zero memory indexing overhead',
          'HNSW provides logarithmic search time with superior recall-latency tradeoff without retraining centroids',
          'HNSW executes exclusively on GPU VRAM',
          'IVFFlat always yields higher accuracy at high dimensions'
        ],
        correctAnswer: 1,
        explanation: 'HNSW builds multi-layer graph structures delivering near sub-linear search latency and high recall even without cluster retraining.'
      }
    ]
  },
  {
    id: 'asm-3',
    title: 'Cloud Native & Kubernetes Pod Lifecycle',
    category: 'Cloud',
    durationMinutes: 30,
    questionsCount: 10,
    difficulty: 'Medium',
    skillsEvaluated: ['K8s Probes', 'Ingress', 'Helm', 'CSI Storage'],
    passingScore: 70,
    completed: false,
    questions: [
      {
        id: 'q-cl-1',
        question: 'When should a startupProbe be configured in a Kubernetes pod specification?',
        options: [
          'To continuously check if the app is alive during normal operation',
          'For legacy or slow-starting containers to prevent readiness/liveness probes killing the pod prematurely',
          'To manage persistent volume mounting timeouts',
          'To route external ingress traffic before DNS propagation'
        ],
        correctAnswer: 1,
        explanation: 'startupProbe disables liveness and readiness checks until it succeeds, protecting slow-booting applications from aggressive restarts.'
      }
    ]
  },
  {
    id: 'asm-4',
    title: 'Analytical Aptitude & Quantitative Reasoning',
    category: 'Aptitude',
    durationMinutes: 35,
    questionsCount: 20,
    difficulty: 'Medium',
    skillsEvaluated: ['Data Interpretation', 'Probability', 'Logical Deduction'],
    passingScore: 75,
    completed: true,
    score: 92,
    percentile: 95.8,
  },
  {
    id: 'asm-5',
    title: 'Executive Technical Communication',
    category: 'Communication',
    durationMinutes: 25,
    questionsCount: 10,
    difficulty: 'Easy',
    skillsEvaluated: ['Stakeholder Sync', 'Architecture Diagrams', 'Incident Post-Mortems'],
    passingScore: 70,
    completed: true,
    score: 85,
    percentile: 89.2,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    studentName: 'Devansh Kulkarni',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 942,
    verifiedSkillsCount: 9,
    badge: 'Elite Vanguard',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 2,
    studentName: 'Priya Nambiar',
    college: 'National Tech University',
    department: 'AIML',
    builderScore: 918,
    verifiedSkillsCount: 8,
    badge: 'Master Architect',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 3,
    studentName: 'Aarav Sharma (You)',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    builderScore: 885,
    verifiedSkillsCount: 6,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 4,
    studentName: 'Rohan Mehra',
    college: 'Metropolitan Institute of Science',
    department: 'IT',
    builderScore: 864,
    verifiedSkillsCount: 7,
    badge: 'Lead Builder',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
  {
    rank: 5,
    studentName: 'Ananya Iyer',
    college: 'Southern Institute of Engineering',
    department: 'ECE',
    builderScore: 842,
    verifiedSkillsCount: 5,
    badge: 'Senior Builder',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
  },
];

export const mockRoleSkillGap: Record<string, RoleSkillGapAnalysis> = {
  'AI Engineer': {
    targetRole: 'AI Engineer',
    matchPercentage: 86,
    totalRequiredSkills: 8,
    matchedSkillsCount: 6,
    missingSkills: ['Kubernetes / Triton Inference Server', 'Graph Neural Networks & DGL'],
    overview: 'Strong foundation in Python, Vector DBs, and LLM orchestration. You are 2 critical infrastructure skills away from 95%+ enterprise alignment.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'PyTorch & Transformers',
        requiredLevel: 'Expert',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 90,
        recommendedCourse: 'Deep Learning Systems Architecture',
      },
      {
        skill: 'pgvector & Vector Databases',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed (Verified)',
      },
      {
        skill: 'LLM Orchestration & RAG',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 92,
        recommendedCourse: 'Advanced Agentic Patterns with LangGraph',
      },
      {
        skill: 'Triton Inference Server / vLLM',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 20,
        recommendedCourse: 'High-Throughput Model Serving with vLLM & TensorRT',
      },
      {
        skill: 'Distributed Training (FSDP / DeepSpeed)',
        requiredLevel: 'Intermediate',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 45,
        recommendedCourse: 'Distributed Machine Learning at Scale',
      },
    ],
  },
  'Backend Developer': {
    targetRole: 'Backend Developer',
    matchPercentage: 92,
    totalRequiredSkills: 7,
    matchedSkillsCount: 6,
    missingSkills: ['Kafka / Event-Driven Architecture'],
    overview: 'Exceptional backend capabilities with proven SQL performance, API design, and asynchronous concurrency.',
    skillGaps: [
      {
        skill: 'Python & FastAPI',
        requiredLevel: 'Advanced',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PostgreSQL Optimization',
        requiredLevel: 'Advanced',
        currentLevel: 'Advanced',
        gapSeverity: 'Low',
        matchScore: 95,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'Kafka Message Queuing',
        requiredLevel: 'Advanced',
        currentLevel: 'Beginner',
        gapSeverity: 'High',
        matchScore: 40,
        recommendedCourse: 'Enterprise Event Streaming with Apache Kafka',
      },
    ],
  },
  'Data Analyst': {
    targetRole: 'Data Analyst',
    matchPercentage: 78,
    totalRequiredSkills: 6,
    matchedSkillsCount: 4,
    missingSkills: ['PowerBI / Tableau', 'Advanced Business Statistics'],
    overview: 'Solid programmatic and SQL foundation; needs dashboarding and executive stakeholder KPI modeling practice.',
    skillGaps: [
      {
        skill: 'SQL Querying',
        requiredLevel: 'Expert',
        currentLevel: 'Expert',
        gapSeverity: 'Low',
        matchScore: 100,
        recommendedCourse: 'Completed',
      },
      {
        skill: 'PowerBI / Tableau',
        requiredLevel: 'Advanced',
        currentLevel: 'None',
        gapSeverity: 'Critical',
        matchScore: 15,
        recommendedCourse: 'Executive BI & Dashboards Masterclass',
      },
    ],
  },
};

export const mockRoadmapPhases: RoadmapPhase[] = [
  {
    id: 'phase-1',
    phaseNumber: 1,
    title: 'Foundation',
    description: 'Master core algorithmic problem solving, modern Python 3.12+, and relational database schema design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Advanced Data Structures & Algorithms', provider: 'SkillBridge Core', duration: '6 weeks', completed: true },
      { title: 'High Performance Python & Concurrency', provider: 'SkillBridge Core', duration: '4 weeks', completed: true },
    ],
    projects: [
      { title: 'Concurrent Cache with LRU & TTL Eviction', description: 'Thread-safe in-memory key-value store', techStack: ['Python', 'Threading', 'TCP Sockets'], completed: true },
    ],
    assessments: [
      { title: 'Data Structures Benchmark', category: 'Programming', completed: true },
      { title: 'Quantitative Aptitude Level 1', category: 'Aptitude', completed: true },
    ],
  },
  {
    id: 'phase-2',
    phaseNumber: 2,
    title: 'Core',
    description: 'Deep dive into REST & gRPC API architecture, vector databases (pgvector), and modern microservice design.',
    status: 'completed',
    progressPercentage: 100,
    courses: [
      { title: 'Production FastAPI & Distributed Systems', provider: 'Coursera Enterprise', duration: '5 weeks', completed: true },
      { title: 'Vector Embeddings & Semantic Search', provider: 'DeepLearning.AI', duration: '3 weeks', completed: true },
    ],
    projects: [
      { title: 'Hybrid Lexical-Vector Search Engine', description: 'Sub-20ms multi-tenant vector retriever on PostgreSQL', techStack: ['FastAPI', 'pgvector', 'Redis'], completed: true },
    ],
    assessments: [
      { title: 'Advanced Python & Concurrency Benchmark', category: 'Programming', completed: true },
    ],
  },
  {
    id: 'phase-3',
    phaseNumber: 3,
    title: 'Advanced',
    description: 'LLM fine-tuning, Quantization (4-bit/8-bit), RAG evaluation metrics (Ragas), and Triton inference pipelines.',
    status: 'in_progress',
    progressPercentage: 65,
    courses: [
      { title: 'LLM Inference Optimization & vLLM Internals', provider: 'SkillBridge Masterclass', duration: '4 weeks', completed: true },
      { title: 'Kubernetes for Machine Learning Workloads', provider: 'Cloud Native Academy', duration: '4 weeks', completed: false },
    ],
    projects: [
      { title: 'Enterprise Document Intelligence with LangGraph', description: 'Autonomous agentic multi-doc synthesis pipeline', techStack: ['FastAPI', 'LangGraph', 'Docker'], completed: true },
      { title: 'Triton Server TensorRT Deployment', description: 'Deploying quantized Mistral-7B at 80 tokens/sec', techStack: ['Triton', 'TensorRT-LLM', 'CUDA'], completed: false },
    ],
    assessments: [
      { title: 'LLM Engineering & Vector Search Architecture', category: 'AI', completed: true },
      { title: 'Cloud Native & Kubernetes Pod Lifecycle', category: 'Cloud', completed: false },
    ],
  },
  {
    id: 'phase-4',
    phaseNumber: 4,
    title: 'Industry Ready',
    description: 'System design capstone, live client simulations, mock technical interviews, and recruiter talent discovery indexing.',
    status: 'locked',
    progressPercentage: 0,
    courses: [
      { title: 'Large Scale Distributed System Design', provider: 'SkillBridge Enterprise', duration: '4 weeks', completed: false },
      { title: 'AI Ethics, Guardrails & SOC2 Compliance', provider: 'Security Institute', duration: '2 weeks', completed: false },
    ],
    projects: [
      { title: 'Full-Scale Enterprise Workforce Intelligence Platform', description: 'Multi-tenant high-availability microservices', techStack: ['Next.js 15', 'FastAPI', 'PostgreSQL', 'K8s'], completed: false },
    ],
    assessments: [
      { title: 'Full Enterprise Architecture Capstone Exam', category: 'Programming', completed: false },
    ],
  },
];

export const mockInternships: InternshipOpportunity[] = [
  {
    id: 'job-101',
    role: 'AI Infrastructure Engineer Intern',
    company: 'Anthropic Labs Partner Network',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    location: 'San Francisco, CA (Hybrid / Remote)',
    type: 'Hybrid',
    stipend: '$7,500 / month',
    duration: '6 Months',
    matchScore: 94,
    requiredSkills: ['Python', 'PyTorch', 'Vector Search', 'FastAPI'],
    postedDate: '2 days ago',
    applied: false,
    applicantsCount: 42,
    description: 'Help architect low-latency inference pipelines and multi-tenant vector indexes for next-generation intelligence tooling.',
  },
  {
    id: 'job-102',
    role: 'Backend Platform Engineer Intern',
    company: 'Stripe Scale Program',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    location: 'New York, NY (On-site)',
    type: 'On-site',
    stipend: '$8,200 / month',
    duration: '3 Months',
    matchScore: 91,
    requiredSkills: ['Python', 'PostgreSQL', 'Distributed Systems', 'Docker'],
    postedDate: '3 days ago',
    applied: true,
    applicantsCount: 118,
    description: 'Work alongside core payments infrastructure teams optimizing high-throughput transaction ledgers and microservices.',
  },
  {
    id: 'job-103',
    role: 'Full-Stack AI Software Intern',
    company: 'Linear Ventures',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    location: 'Remote',
    type: 'Remote',
    stipend: '$6,800 / month',
    duration: '6 Months',
    matchScore: 88,
    requiredSkills: ['TypeScript', 'Next.js', 'FastAPI', 'Tailwind CSS'],
    postedDate: '5 days ago',
    applied: false,
    applicantsCount: 67,
    description: 'Build polished, responsive user interfaces and robust APIs for automated sprint intelligence and code analysis.',
  },
];

// Institute Portal Seed Data
export const mockDepartmentMetrics: DepartmentMetric[] = [
  {
    name: 'CSE',
    totalStudents: 320,
    overallReadiness: 86,
    programming: 91,
    cloud: 78,
    ai: 88,
    devOps: 74,
    dataScience: 82,
  },
  {
    name: 'AIML',
    totalStudents: 180,
    overallReadiness: 89,
    programming: 88,
    cloud: 72,
    ai: 95,
    devOps: 68,
    dataScience: 94,
  },
  {
    name: 'IT',
    totalStudents: 240,
    overallReadiness: 81,
    programming: 84,
    cloud: 85,
    ai: 70,
    devOps: 82,
    dataScience: 75,
  },
  {
    name: 'ECE',
    totalStudents: 210,
    overallReadiness: 72,
    programming: 75,
    cloud: 60,
    ai: 66,
    devOps: 58,
    dataScience: 69,
  },
];

export const mockCurriculumAnalysis: CurriculumAnalysisResult = {
  syllabusTitle: 'B.Tech CSE - 6th Semester Advanced Computing Curriculum (2025-2026)',
  department: 'Computer Science & Engineering',
  semester: '6th Semester',
  industryRelevanceScore: 78,
  totalTopicsAnalyzed: 44,
  modernTopicsCount: 31,
  missingTopics: [
    {
      topic: 'Vector Databases & Embedding Indexing (HNSW / pgvector)',
      importance: 'Critical',
      industryUsagePercentage: 88,
      recommendedModule: 'Module 4: Advanced Data Storage & RAG Systems',
    },
    {
      topic: 'Cloud Native CI/CD & Kubernetes Manifests',
      importance: 'Critical',
      industryUsagePercentage: 92,
      recommendedModule: 'Module 5: Modern DevOps & Container Orchestration',
    },
    {
      topic: 'LLM Fine-Tuning, Quantization & Prompt Optimization',
      importance: 'High',
      industryUsagePercentage: 84,
      recommendedModule: 'Module 3: Contemporary Applied Machine Intelligence',
    },
    {
      topic: 'gRPC & Protocol Buffers for Low-Latency Microservices',
      importance: 'Moderate',
      industryUsagePercentage: 76,
      recommendedModule: 'Module 2: Distributed Systems Communication',
    },
  ],
  outdatedTopics: [
    'SOAP XML Web Services & WSDL Specifications',
    'CORBA Distributed Object Architectures',
    'Legacy JSP / Servlet Form Submissions',
  ],
  suggestedImprovements: [
    'Replace legacy SOAP XML laboratory exercises with OpenAPI 3.1 & FastAPI Async handlers.',
    'Introduce 4 weeks of hands-on containerization labs (Docker Compose + K8s MiniKube).',
    'Integrate vector search laboratory modules using PostgreSQL + pgvector for unstructured retrieval.',
    'Align assessment rubrics with GitHub Builder evidence and automated unit-test grading.',
  ],
  topSkillsCovered: ['Data Structures', 'Operating Systems', 'RDBMS & SQL', 'Computer Networks', 'Intro to ML'],
};

// Industry Portal Seed Data
export const mockJobRequirements: JobRequirement[] = [
  {
    id: 'req-201',
    title: 'AI Systems Engineer (Graduate 2026)',
    department: 'Applied AI',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'Bangalore / Hyderabad (Hybrid)',
    type: 'Full-Time',
    salaryRange: '$85,000 - $115,000',
    minMatchScore: 80,
    requiredSkills: ['Python', 'PyTorch', 'FastAPI', 'pgvector', 'Docker'],
    preferredSkills: ['vLLM', 'Kubernetes', 'LangGraph'],
    activeApplicants: 34,
    createdAt: 'Mar 01, 2026',
    status: 'Active',
  },
  {
    id: 'req-202',
    title: 'Full-Stack SaaS Platform Engineer',
    department: 'Core Product',
    experienceLevel: 'Associate (1-3 yrs)',
    location: 'Remote (US/India)',
    type: 'Full-Time',
    salaryRange: '$90,000 - $125,000',
    minMatchScore: 75,
    requiredSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind CSS'],
    preferredSkills: ['Redis', 'AWS Lambda', 'GraphQL'],
    activeApplicants: 52,
    createdAt: 'Feb 24, 2026',
    status: 'Active',
  },
  {
    id: 'req-203',
    title: 'Cloud Infrastructure & DevOps Intern',
    department: 'Site Reliability',
    experienceLevel: 'Entry Level (0-1 yrs)',
    location: 'San Francisco, CA',
    type: 'Internship',
    salaryRange: '$6,000 / month',
    minMatchScore: 70,
    requiredSkills: ['Docker', 'Kubernetes', 'Linux Internals', 'Python/Go'],
    preferredSkills: ['Terraform', 'Prometheus', 'Grafana'],
    activeApplicants: 19,
    createdAt: 'Feb 28, 2026',
    status: 'Active',
  },
];

export const mockCandidatesPipeline: CandidateApplication[] = [
  {
    id: 'cand-1',
    studentId: 'std-98214',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 885,
    employabilityScore: 91,
    matchScore: 94,
    stage: 'Interview',
    appliedDate: 'Mar 03, 2026',
    topSkills: ['Python', 'FastAPI', 'PyTorch', 'pgvector'],
    githubUrl: 'https://github.com/aarav-sharma-builder',
  },
  {
    id: 'cand-2',
    studentId: 'std-98215',
    name: 'Devansh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    college: 'Apex Institute of Technology',
    department: 'CSE',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 942,
    employabilityScore: 96,
    matchScore: 98,
    stage: 'Selected',
    appliedDate: 'Mar 01, 2026',
    topSkills: ['Python', 'C++', 'CUDA', 'Distributed Systems'],
    githubUrl: 'https://github.com/devansh-k-vanguard',
  },
  {
    id: 'cand-3',
    studentId: 'std-98216',
    name: 'Priya Nambiar',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    college: 'National Tech University',
    department: 'AIML',
    targetRole: 'AI Systems Engineer',
    jobId: 'req-201',
    builderScore: 918,
    employabilityScore: 93,
    matchScore: 92,
    stage: 'Assessment',
    appliedDate: 'Mar 04, 2026',
    topSkills: ['PyTorch', 'Transformers', 'FastAPI', 'MLOps'],
    githubUrl: 'https://github.com/priya-nambiar-ai',
  },
  {
    id: 'cand-4',
    studentId: 'std-98217',
    name: 'Rohan Mehra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    college: 'Metropolitan Institute of Science',
    department: 'IT',
    targetRole: 'Full-Stack SaaS Platform Engineer',
    jobId: 'req-202',
    builderScore: 864,
    employabilityScore: 89,
    matchScore: 88,
    stage: 'Shortlisted',
    appliedDate: 'Mar 05, 2026',
    topSkills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Tailwind'],
    githubUrl: 'https://github.com/rohan-mehra-dev',
  },
  {
    id: 'cand-5',
    studentId: 'std-98218',
    name: 'Ananya Iyer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
    college: 'Southern Institute of Engineering',
    department: 'ECE',
    targetRole: 'Cloud Infrastructure & DevOps Intern',
    jobId: 'req-203',
    builderScore: 842,
    employabilityScore: 86,
    matchScore: 85,
    stage: 'Matched',
    appliedDate: 'Mar 06, 2026',
    topSkills: ['Docker', 'Linux', 'Python', 'K8s'],
    githubUrl: 'https://github.com/ananya-iyer-cloud',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-1',
    title: 'High-Throughput Vector Index Benchmark in Python/C++',
    type: 'Coding Test',
    roleTarget: 'AI Systems Engineer',
    duration: '90 mins',
    totalAssigned: 45,
    submissionsCount: 38,
    averageScore: 82.4,
    status: 'Active',
    dueDate: 'Mar 18, 2026',
  },
  {
    id: 'asg-2',
    title: 'Enterprise Multi-Tenant SaaS DB Schema Design',
    type: 'Case Study',
    roleTarget: 'Full-Stack Platform Engineer',
    duration: '2 Days Takehome',
    totalAssigned: 30,
    submissionsCount: 26,
    averageScore: 88.0,
    status: 'Active',
    dueDate: 'Mar 20, 2026',
  },
  {
    id: 'asg-3',
    title: 'Fault-Tolerant K8s Pod Scheduling Simulator',
    type: 'System Design Challenge',
    roleTarget: 'Cloud Infrastructure Intern',
    duration: '120 mins',
    totalAssigned: 22,
    submissionsCount: 19,
    averageScore: 76.5,
    status: 'Active',
    dueDate: 'Mar 22, 2026',
  },
];

// Admin Portal Seed Data
export const mockSkillDemandMetrics: SkillDemandMetric[] = [
  {
    skill: 'LLM Orchestration & RAG',
    category: 'AI / Machine Learning',
    demandPercentage: 94,
    growthRate: 148,
    avgSalary: '$145,000',
    openRolesCount: 4280,
    demandTrend: [
      { month: 'Oct', value: 65 },
      { month: 'Nov', value: 74 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 94 },
    ],
  },
  {
    skill: 'Python & FastAPI',
    category: 'Backend Programming',
    demandPercentage: 91,
    growthRate: 42,
    avgSalary: '$130,000',
    openRolesCount: 6120,
    demandTrend: [
      { month: 'Oct', value: 82 },
      { month: 'Nov', value: 85 },
      { month: 'Dec', value: 87 },
      { month: 'Jan', value: 89 },
      { month: 'Feb', value: 91 },
    ],
  },
  {
    skill: 'TypeScript & Next.js 15',
    category: 'Full-Stack Web',
    demandPercentage: 88,
    growthRate: 64,
    avgSalary: '$125,000',
    openRolesCount: 5490,
    demandTrend: [
      { month: 'Oct', value: 76 },
      { month: 'Nov', value: 80 },
      { month: 'Dec', value: 83 },
      { month: 'Jan', value: 86 },
      { month: 'Feb', value: 88 },
    ],
  },
  {
    skill: 'Vector DBs (pgvector / Pinecone)',
    category: 'Database Systems',
    demandPercentage: 86,
    growthRate: 185,
    avgSalary: '$140,000',
    openRolesCount: 3850,
    demandTrend: [
      { month: 'Oct', value: 50 },
      { month: 'Nov', value: 62 },
      { month: 'Dec', value: 73 },
      { month: 'Jan', value: 81 },
      { month: 'Feb', value: 86 },
    ],
  },
  {
    skill: 'Kubernetes & Cloud Native',
    category: 'DevOps & Infra',
    demandPercentage: 85,
    growthRate: 38,
    avgSalary: '$138,000',
    openRolesCount: 4900,
    demandTrend: [
      { month: 'Oct', value: 79 },
      { month: 'Nov', value: 81 },
      { month: 'Dec', value: 82 },
      { month: 'Jan', value: 84 },
      { month: 'Feb', value: 85 },
    ],
  },
];

export const mockPlatformUsers: PlatformUser[] = [
  {
    id: 'usr-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@stanford.edu',
    role: 'student',
    organization: 'Apex Institute of Technology',
    status: 'Active',
    joinedDate: 'Sep 2024',
    activityScore: 98,
  },
  {
    id: 'usr-2',
    name: 'Dr. Radhika Sen',
    email: 'radhika.sen@apexinstitute.edu',
    role: 'institute',
    organization: 'Apex Institute of Technology (Dean)',
    status: 'Active',
    joinedDate: 'Aug 2024',
    activityScore: 92,
  },
  {
    id: 'usr-3',
    name: 'Marcus Vance',
    email: 'marcus.vance@anthropic-partner.io',
    role: 'industry',
    organization: 'Anthropic Labs Partner Network',
    status: 'Active',
    joinedDate: 'Nov 2024',
    activityScore: 95,
  },
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena@skillbridge.ai',
    role: 'admin',
    organization: 'SkillBridge Global Systems',
    status: 'Active',
    joinedDate: 'Jan 2024',
    activityScore: 100,
  },
];
